### ISSUE TITLE
v.redd.it mouseover support

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#10]
If you visit this link: [v.redd.it links](https://old.reddit.com/domain/v.redd.it/), you can see a list of mostly short embedded videos. You can distinguish video thumbnails from image thumbnails because video thumbnails have a sibling `div` element with `class="duration-overlay"`. Once the video is expanded by clicking the "Play" button, you can find the elements containing two links: a .mpd file, e.g.: `data-mpd-url="https://v.redd.it/4htp0060enj41/DASHPlaylist.mpd"` and the .m3u8 file: `data-hls-url="https://v.redd.it/4htp0060enj41/HLSPlaylist.m3u8"`. I don't know if MPIV is capable of playing either of these formats directly, though.

**Comment by tophf** [comment]
Those videos don't have a directly linkable source. The site uses an elaborate video player that fetches the source in chunks and assembles into a blob. MPIV can't use that.
