### ISSUE TITLE
MPIV interferes with XML rendering in Firefox

### ISSUE THREAD

**Issue by em-ex** [tophf/mpiv#105]
#### Steps to reproduce the bug
1. Enable MPIV in Tampermonkey
2. Navigate to any XML file in Firefox
3. XML document is rendered as plain text with all tags and linebreaks stripped

#### Expected behavior
The XML document is rendered as collapsible tree

#### Screenshots
![image](https://user-images.githubusercontent.com/29741946/191645448-8cd65226-2639-4141-8d7c-c10d0b35cdae.png)
MPIV enabled
![image](https://user-images.githubusercontent.com/29741946/191645230-97c285a4-b177-40f6-bd3a-2ae5bea13312.png)
MPIV disabled

#### Environment
 - Browser: Firefox 105 + Tampermonkey 4.17.6161
 - MPIV Version: 1.2.27

**Comment by tophf** [comment]
It's a problem in Tampermonkey itself: if any script at all is running on an xml page, TM breaks its styles. There is no workaround, AFAIK, other than using a different API to run the scripts e.g. in Violentmonkey we use browser.tabs.executeScript, in Greasemonkey/Firemonkey they use browser.userScripts.

**Comment by em-ex** [comment]
Thank you for the explanation! I had a suspicion that it could be the case. Too bad I can't remember why I chose TM over Violentmonkey — looks like I'm going to find out again
