### ISSUE TITLE
Make fading top info bar optional

### ISSUE THREAD

**Issue by Richard-L** [tophf/mpiv#109]
Thank you so much for improving this extension - after so many years, it's still so useful.

Could you tell me which lines need to be commented out in order to completely hide the info bar showing on top of images?
![image](https://github.com/tophf/mpiv/assets/4934209/cb30bead-0879-410b-877f-15e8ecbeca0f)

Or could you make it optional whether it's showing or not? I would prefer to not see it.
Thanks a lot.

**Comment by tophf** [comment]
Put this in Custom CSS in the options:
```css
#mpiv-bar { display: none }
```

**Comment by Richard-L** [comment]
Thank you very much 🙏
