### ISSUE TITLE
Don't close popup when the mouse goes too far vertically

### ISSUE THREAD

**Issue by musjj** [tophf/mpiv#112]
When the popup is open, moving the mouse too far up or too far down will automatically close the popup. Can we have an option to disable this behavior?

**Comment by tophf** [comment]
The popup is shown when you hover the original element. You can hold `Shift` or zoom the image to enable free mouse movement. I can add an option of course, but I'd like to know first why do you need it constantly enabled?

**Comment by musjj** [comment]
When I zoom in on a large image while moving my mouse to pan across the image, I often accidentally move the mouse too far vertically. This closes the popup, forcing me to re-open it, zoom again, etc.

It certainly would be nice to have a way to disable this.

**Comment by tophf** [comment]
If you enable `Keep preview on blur` it'll persist when you switch tabs or move the pointer outside the bounds of the tab.

**Comment by musjj** [comment]
Thanks, that's perfect! I'll consider this issue solved.
