### ISSUE TITLE
Instagram galleries not working properly

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#12]
Visit any instagram page such as: [instagram.com/instagram](https://www.instagram.com/instagram).

Galleries seem to behave unpredictably. Sometimes, hitting the right or left keyboard keys will work properly, sometimes it will immediately close the popup, and sometimes it will start from the last image in the gallery and cycle towards the first image.

Might be a recent regression as I didn't notice this when the feature was first implemented a couple of days ago.

**Comment by tophf** [comment]
Well, I can't reproduce the unpredictability part so I don't think I can do anything about that.

I fixed the direction of keyboard navigation though, which I recently reverted by accident.

**Comment by Ryujinra** [comment]
So the popup doesn't close unless I am still hovered over the gallery when I hit the left or right keys; if I hover the first image, then move the mouse to the side of the screen, keyboard navigation works as expected. But if I keep the mouse in place after hovering,  hitting the keyboard key causes it to to immediately try to reload the gallery - it's like there is a brief moment in between cycling images when the mouse is allowed to reach below the image, which starts loading the gallery again.

**Comment by tophf** [comment]
Wow, nice find!

**Comment by tophf** [comment]
Should be fixed now in `master`.
Apparently I've never used keyboard nav in galleries.

**Comment by Ryujinra** [comment]
Yep, keyboard nav appears to be fixed for me. I noticed mousewheel cycles galleries now instead of zooming, but then I have two questions:

1) Can we have a configuration option to return to the original behavior? It seems more intuitive to me to have mousewheel always have the behavior of zooming in/out, and cycle galleries with some other mechanism like keyboard nav. At the very least, is there a shortcut key so manually trigger zoom status so we can zoom individual images in galleries? As of now, I can't figure out how to zoom galleries if zoom is set to 'Automatically' to start with.

2) Cycling through images with "MOUSEWHEEL UP" seems to fail sometimes, causing the image to zoom slightly, then be refit to the window instead (if `fit to window` is on). It seems that it alternates between wanting to cycle and wanting to zoom, and this is tied to the rate of moving the wheel. Move it very slow and it tries (and fails) to zoom in - move it fast and it cycles the image instead.

**Comment by tophf** [comment]
re 1, no, the original behavior in MPIV has always been to cycle the gallery so I won't be changing that. You can press <kbd>Shift</kbd> to toggle zoom mode.

re 2, couldn't reproduce. I wonder if this is your dpi thing in about:config...

**Comment by tophf** [comment]
Actually I can't reproduce your \#1 either: when zooming is set to activate automatically.

**Comment by Ryujinra** [comment]
Yeah it seems to work for me as well now too, unsure of what the issue was. To be clear, if you have zoom set to `Automatically` my desired behavior works fine: gallery starts in `zoomed mode` and mousewheel zooms the current image, keyboard nav cycles the image, etc.
