### ISSUE TITLE
Gallery popup seems unable to set up properly in some cases

### ISSUE THREAD

**Issue by JarheadHME** [tophf/mpiv#123]
#### Steps to reproduce the bug
1. Visit https://old.reddit.com/r/TheOdysseyHadAPurpose/comments/1h5bz8t/fumo/ (or any similar post on old reddit at least)
2. Create custom rule of:
```json
{
 "d": "old.reddit.com",
 "r": "reddit\\.com/gallery/.+",
 "g": "var nodes = doc.querySelectorAll(\"a.iUP9nbvcaxfwKrQTgt0sw\"); var all_links = []; for (var curr_node of nodes) { var preclean_link = curr_node.getAttribute(\"href\"); if (preclean_link === null) continue; var match = preclean_link.match(/.*redd\\.it\\/(\\w+\\.\\w+)\\?.*/); var link = \"https://i.redd.it/\" + match[1]; all_links.push(link); } var map = all_links.map(i=>({url:i,desc:\"\"})); map.index = 0; return map;"
}
```
(yes the rule is very bad, I was just trying to get it to work before I cleaned it up when I finally realized that the gallery itself seemed to not be)
3. Hover over the post title and find that no gallery pops up

#### Expected behavior
Gallery pops up

#### Screenshots
![ca4b950227102bf6](https://github.com/user-attachments/assets/e8c85074-ffdf-4cef-af41-90fe70d111c3)

#### Environment
 - Browser: Firefox
 - MPIV Version: 1.4.6

**Comment by tophf** [comment]
It works for me in Chrome, I'll check later in Firefox.

**Comment by JarheadHME** [comment]
ok
i went and tried it in edge
then went and copied the script back into firefox and suddenly it worked
i'm so confused but whatever lol
