### ISSUE TITLE
Instagram rule incorrectly matches comment section

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#14]
The new Instagram rule triggers when mouse is over the comment section because that element also has the `role="button"` attribute. Will probably have to use the `tabindex` attribute as well to further restrict matching to the image's div container.

Changing the relevant part of the rule to this:
`e: 'a[href*="/p/"], article [role="button"][tabindex="0"], article [role="button"][tabindex="0"] div',`

has added benefit of matching the profile images in the comment section and zooming their larger versions, and seems to fix the issue.

**Comment by tophf** [comment]
Great, added in b93b0ef2.
