### ISSUE TITLE
Appearance options bugs/notes

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#18]
I don't personally use these as I just use the custom CSS styling for whatever changes I want, but I tested it anyway and found some quirks:

1. `Padding` just pads the top part of the image and shifts the whole image down in `fit-to-window` mode (maybe other modes as well), I assume the expected behavior is padding all sides.

2. The sliders are small so getting a precise value is difficult especially since there is no visual feedback (of the updated value) as you are adjusting the slider over short distances. You currently need to adjust, then rehover to update tooltip, and repeat, over and over to get, say `70%` opacity set correctly. I think these should be standard input fields. This would also allow setting more granular values like `0.5px` as well, but it's your call obviously. 

At the very least, the tooltip should be properly updated with the slider's current position whenever the slider position moves (as it is, the tooltip is only updated when you move over about 25% of the distance from the current point, otherwise it just displays the original value). To reproduce, set `50%` opacity, then slowly slide to the left or right, you won't see the tooltip value update.

3. All of these values stomp over the custom CSS style settings (because they all have `!important` and due to the ordering?). So you can't set custom `border` values anymore in the CSS style area.

**Comment by tophf** [comment]
> Padding

Can't repro. Do you have custom CSS as well?

> The sliders are small so getting a precise value is difficult

Simply use the keyboard arrows to adjust the values precisely once the input is focused. Anyway, these options are for visual people. I used numeric inputs at first but then decided against it. For 0.5px and other weird stuff use the custom CSS.

> So you can't set custom border values anymore in the CSS style area.

But you can. Simply add `!important to your rules`. You can also use "View the built-in CSS" to copy from the currently applied code.
```css
#mpiv-popup.mpiv-show {
  border: 3px solid red !important;
}
```

**Comment by Ryujinra** [comment]
Oops it's actually `margin` which just pushes the image down for me, whereas I expected it to adjust margins on all sides.

`!important` doesn't always work for me; the reason I think something is going wrong is `box-shadow: none !important;` doesn't work anymore to remove the drop-shadow.

**Comment by tophf** [comment]
Yeah, I see it with a margin.

**Comment by tophf** [comment]
Margin calc should be fixed now.
And the shadow will be disabled when its size is set to 0.
As for the rest, it's not yet set in stone, I'll be improving the UI.

**Comment by tophf** [comment]
Now an extra number input is shown when the slider is focused.

**Comment by Ryujinra** [comment]
Cool idea that doesn't take up extra space. Settings for the sliders don't seem to be saved anymore though; they reset to default when I open the configuration window.

**Comment by tophf** [comment]
Saves for me. Did you actually click Save or Apply?

**Comment by Ryujinra** [comment]
Yep, and other settings save fine; just the sliders that reset. I'll pull a fresh master just in case it's one of my minor changes on my local branch.

**Comment by Ryujinra** [comment]
Yeah they mostly all default to the middle of the slider; except shadow opacity defaults to 80 and background opacity defaults to 100.

**Comment by tophf** [comment]
And does it work for you in the previous commit?

**Comment by Ryujinra** [comment]
Yes, just checked. Reverted, settings worked fine. Then I pulled latest commit, tested and seemed to be working fine, but once I refreshed the page (and presumably reloaded the script) the slider settings were reverted to the defaults.

**Comment by tophf** [comment]
Aha! Reloading the page was the missing step.

**Comment by tophf** [comment]
Turns out it did save but wasn't rendered properly in the config.

**Comment by Ryujinra** [comment]
Yep, works and remembered my old settings for those values.
