### ISSUE TITLE
Feature request: Ability to show bar for galleries only

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#20]
The original MPIV would only show the bar when a gallery was hovered; I can't see how to replicate that behavior with current MPIV features.

Right now, I have hidden the bar with CSS, but then I can't know know when I'm hovering an `imgur` gallery, for instance, so I don't know when there are extra images. 

A separate class for denoting when galleries were loaded would make this possible again.

**Comment by tophf** [comment]
```css
#mpiv-bar:not(.mpiv-gallery) {
  display: none;
}
```
