### ISSUE TITLE
With very large images, border and background are shown before image loads

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#21]
For large images, the border/background loads significantly faster than the image; hover the image on this page: [large landscape](https://old.reddit.com/r/wallpapers/comments/fhupsp/pucture_at_horseshoe_bend_i_took_yesterday/). You should see the border/background load very quickly, but the image loads in afterwards. Ideally, I think the border/background should delay displaying until the image is ready to be displayed. I tried using the `loaded` class but it doesn't seem to help here.

Related(?) side note: I originally tried hotlinking the image above, but it actually reproducibly crashed my browser. Does hovering this link work for you? [hotlink to landscape image](https://i.redd.it/vkmc6wlnldm41.jpg)

**Comment by tophf** [comment]
I'm not sure what to do here because when a transparent picture is being loaded without a background it looks really ugly and messy. I guess I can екн checkштп the extension and apply the background/border early only for PNG. It will miss some cases where the URL doesn't have an extension though. I'm pretty pessimistic about it now because it sounds like something random.

**Comment by tophf** [comment]
Actually I couldn't reproduce as those images load quickly for me.
The styles seem fine as they set the background only on `[loaded]` or `.mpiv-show`.

**Comment by Ryujinra** [comment]
The thing is, even if I set the background to transparent, the border still shows up before the image is loaded. Applying the border on `[loaded]` only seems to wait for the _popup_ to load and not necessarily the image itself. Not sure how you could reproduce if they load fast for you (maybe a bandwidth limiter?). I'm on a 1gbit fiber connection, but an older laptop, so it's probably my processor causing the delay while it scales the image.

**Comment by tophf** [comment]
Ah, it's probably a recent regression. Try the updated master branch.

**Comment by Ryujinra** [comment]
Might be slightly better now, but still see the background/border before the image on larger images.

**Comment by tophf** [comment]
I'm checking a standard attribute now that should report the completeness so I don't know what I can do better as there's no "rendering completed for this image" event AFAIK.

**Comment by Ryujinra** [comment]
Yeah, even when the image is cached, it still behaves the same way, so it definitely looks like it is just a delay while the image is scaled before it displays. Can you create an attribute at the time the script's scaling is completed, and wait to display until that logic completes?

**Comment by tophf** [comment]
Scaling is a zero-time operation, it's almost as simple as 2+2.

**Comment by Ryujinra** [comment]
Hmm, no idea why I have a noticeable lag time then but it's imperceptibly quick for you; maybe it really is a latency thing despite my fast connection. Have you tried on Firefox?

**Comment by tophf** [comment]
Ah, Firefox, the thing I always forget about. Yeah I see it there, gonna investigate.

**Comment by tophf** [comment]
I absolutely hate FF's devtools and try to avoid using it for extended periods of time so I could only spend 15 minutes on debugging the problem and failed. I have no idea what happens and I don't really care as it seems to be an inherent thing in FF with big images. I've added a delay for this case which seems to "solve" the problem. So it's up to you or anyone who cares about FF to find a way to fix it properly.

**Comment by Ryujinra** [comment]
Does it delay displaying the actual image or just the background/border? I'd rather the image display as fast as it can, even if that means the border/background will appear a little early.

I just started noticing the issue recently, so I will try to bisect the commit where it might have started.

**Comment by tophf** [comment]
The delay (100ms) is added to the entire process. Unless your findings prove otherwise I'm inclined to think this is a bug in FF or an inherent inability to show large images in one paint operation.

**Comment by Ryujinra** [comment]
Found the offending commit: 783e248687d1c4972da3e3345949f1a3f6ed6f73

If I revert to before this commit, either the image loads first and the border/background is applied afterwards, or else they both load imperceptibly close to each other so that I can't notice the delay.

**Comment by tophf** [comment]
Nope, I see the same before that commit. It's also not related to painting as the changes happen a whole lot earlier.

**Comment by tophf** [comment]
>but both behaviors are expected

Why? Definitely sounds like a painting bug in FF and it doesn't happen in Chrome.

**Comment by tophf** [comment]
Actually I see the same in the original MPIV 2017.9.29 so this kinda confirms this is a FF thing.

**Comment by tophf** [comment]
I'll remove the delay because 100ms is often not enough to help FF, I have to raise it to 300ms to suppress the bug for real...  Maybe I'll just add an option.

**Comment by Ryujinra** [comment]
> > but both behaviors are expected
> 
> Why? Definitely sounds like a painting bug in FF and it doesn't happen in Chrome.

I just expect that the image will either load at the same time as the border/background, or styling will follow quickly afterwards, but never that styling appears first.

But yeah it seems like a longstanding issue.

And yes I was just about to say that I didn't notice any real improvement even with the delay. An option would be nice.

I'll see if I can find the exact size at which FF seems to have problems. Maybe we can add the delay at that specific threshold or the option can enable it for images beyond that threshold, so we don't unnecessarily slow down loading for images which don't exhibit the issue.

Such a longstanding bug in FF is unlikely to be high priority in my experience with moz, but I'll probably bring it to their attention and, if it is ever fixed, you can always remove the option/hack later.

**Comment by tophf** [comment]
I found a workaround! Try the new master.

**Comment by Ryujinra** [comment]
Awesome; it's fine 90% of the time now (whereas before, it would delay every single time), and the other 10% of the time, it is significantly faster than before, almost unnoticeable (but maybe this is the recent delay commit interfering?).

**Comment by tophf** [comment]
I've removed the delay.

**Comment by tophf** [comment]
Note, the workaround is applied only if the image size is larger than the browser window.

**Comment by Ryujinra** [comment]
Yeah I believe it happens for very large images only, so that is probably safe.

It's close to perfect now, but I notice the border delay more often (and longer) when the background opacity is set to transparent. No idea why that would be the case, and I have no knowledge of FF's display pipelines, so it's probably best to move on - it's definitely better than it was before.

**Comment by Ryujinra** [comment]
We have a regression from the fix: videos no longer load from instagram/reddit/probably anywhere.

**Comment by Ryujinra** [comment]
It actually starts with the first delay fix commit; not sure if the latest commit is actually causing the issue.

**Comment by tophf** [comment]
Fixed.

**Comment by tophf** [comment]
Had to fix the fix. Twice!
