### ISSUE TITLE
Some videos (maybe  just gfycat?) start playing in the middle after a delay

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#24]
After a recent commit, some videos fail to start playing immediately, and then start somewhere later in the video; hovering and rehovering sometimes makes it play normally.

Go here: [old.reddit.com/domain/gfycat.com](https://old.reddit.com/domain/gfycat.com/) and hover some videos. Some will be frozen at some frame in the middle of the video, and then start playing from there after a delay.

**Comment by tophf** [comment]
Yeah, I didn't test it in Firefox.

**Comment by tophf** [comment]
Probably https://bugzil.la/1582136

**Comment by tophf** [comment]
Actually I don't see any difference to a much older version of MPIV. The only factor I see is those videos have audio and Firefox prevents autoplay on them (spamming the console with an error about that) but does it in a bugged fashion, unlike Chrome.

Anyway, I've switched to a proper method of detecting the fact that autoplay is disabled (using AudioContext API) and it fixed the problem.

**Comment by Ryujinra** [comment]
Sounds good, but there is a regression atm: video detection is broken for me in FF now.

**Comment by tophf** [comment]
What do you mean by "video detection is broken"?

**Comment by Ryujinra** [comment]
Hovering any video doesn't open the popup or do anything; including the link to the gfycat page in the original post.

**Comment by tophf** [comment]
Can't reproduce. Everything is working here even in Firefox ESR.
Do you see any relevant messages in devtools console?

**Comment by Ryujinra** [comment]
`ReferenceError: AudioContext is not defined`

Mightbe related to my security settings. I will try to find out if a firefox configuration option I have set may be causing it.

**Comment by tophf** [comment]
Oh yeah Firefox is "great" in that regard: every essential API can be disabled for imaginary security.

**Comment by Ryujinra** [comment]
Found it: `dom.webaudio.enabled` must be set to to `true` now for it to work.

**Comment by tophf** [comment]
I've added a check so the videos will be muted if AudioContext is not available.

**Comment by Ryujinra** [comment]
Also, video controls show no matter what now, and if you hover the post tiled `How professional ping pong players train` in the original link, it doesn't fit to window properly any more when `fit to window` is set.

**Comment by tophf** [comment]
The controls are shown so you can unmute the videos, which is intentional indeed.

**Comment by Ryujinra** [comment]
The only inconvenience is that if you enable `fit to window`, some videos fill almost the entire viewport, since the aspect ratio is similar to the viewport aspect ratio, so it's hard to exit the video with a left click now on a laptop (or desktop I guess), as you have to move to some non-video space in the window to click.

**Comment by tophf** [comment]
65e7cf23

**Comment by Ryujinra** [comment]
> [65e7cf2](https://github.com/tophf/mpiv/commit/65e7cf2374da39928f386088cd46db7e140e7de2)

Yep, this fixes the issue with the inconsistent zoom behavior for me. By default though, I tend to leave audio on and I mute from the OS if I don't want to hear audio from any videos; is there a way to replicate the old behavior where audio plays automatically and controls aren't displayed? Maybe an option to `show controls` and an option to change the behavior of the automute the script does now?

**Comment by tophf** [comment]
MPIV simply respects your browser's autoplay policy now by reading AudioContext state. If you want to change the way it behaves, then configure your autoplay settings.

**Comment by Ryujinra** [comment]
Yeah it works as expected for me now; I had to refresh the page after disabling `dom.webaudio.enabled` which I had previously enabled for testing. Behavior seems identical to how it was before, and if that option is enabled, the controls are shown and the option to unmute is given, which is perfect.
