### ISSUE TITLE
Regarding the use of the property `"g"` (for gallery rules)

### ISSUE THREAD

**Issue by darkred** [tophf/mpiv#25]
Greetings

<sup>For reference, the relevant lines the script are from [line 933](https://github.com/tophf/mpiv/blob/c9a896937f93aaa738ab55d86355ba8cd0dd860b/script.user.js#L933) to 974.</sup>

This property was not documented by the original MPIV author in his [How to add more rules](https://w9p.co/userscripts/mpiv/host_rules.html)
so I had asked a lot time ago in the greasyfork page https://greasyfork.org/en/forum/discussion/4551/x 
and someone had kindly described me the following:

<details>
<summary>Click to expand</summary>

> kuehlschrank Probably didn't get the time to do that so until then I'll tell you few things I picked, mostly from wOxxOm :
> 
> 1. `"g"` rule is similar to `"q"` rule plus the ability to return multiple photos
> 2. Have the variable text (raw HTTP response / source code of HTML page)
> 3. Also you can manage to have the other two variables `node` and `doc`* *(Firefox only)
> 
> Methods
> 
> 1. Simple selectors 
>     `"g":{"entry":".main","title":".h1","caption":".info","image":".photo","fix":"return s"}`
> 
>     - `"entry"`: used to select main blocks that contain the photos and their captions
>     - `"title"`: (pick text) would show up on the first photo
>     - `"caption"`: (pick text) for each photo
>     - `"image"`: photos
>     - `"fix"`: used to clean the output
> 
>     All are optional except `"image"`
> 
> 2. Using array `"g":"g=[]; r=/regex/g; while(m=r.exec(text)) g.push({url:m}); return g"}`
>     - Creating a regex and have it run on variable text then push photos to `g`
> 
> 3. On Firefox you can create a doc of the raw text doc=createDoc(text) to select from it by `doc.querySelector('')`
</details>

---

**Are the above still valid in this fork?**

And, I have some more questions:

- He said that this `"g"` rule is similar to `"q"` rule. Does this mean that this `"g"` property is only applied to the remote page? 
Can we not use it in the currently loaded page, if it's a gallery itself and contains all the next/previous full image URLs ?
If yes, can this be done via the "array" syntax:
`"g":"g=[]; r=/regex/g; while(m=r.exec(text)) g.push({url:m}); return g"}` ?
- in the "simpler" syntax:
    ```json
    {"d": "example.com",
     "g": {
      "entry": ".main",
      "title": ".h1",
      "caption": ".info",
      "image": ".photo",
      "fix": "return s"
     }
    }
    ```
    what is the `s` in `"fix"` ?
    And, the `"entry"` selector refers to the initial page holding the gallery thumbnail,
    while the `"image"` selector, refers to the remote page?
- Can I use `node` <sup>(element that triggered popup)</sup> and `doc` <sup>(dom tree of remote page)</sup> ? How? Is it still Firefox only?

Thank you

PS. Sorry for the lengthy post!

**Comment by tophf** [comment]
Originally it was only for the remote URLs, but in this fork it can be used on current page as well by specifying `"s":"gallery"`.

For function mode the parameters are:

* `text` - remote response text, undefined in `"s":"gallery"` mode
* `doc` - remote response as `document`, undefined in `"s":"gallery"` mode
* `url` - remote response URL, undefined in `"s":"gallery"` mode
* `m` - the match object/array
* `rule` - the rule object so you can use its properties
* `node` - the original hovered/matched node (added just now in be64fe6c)
* `cb` - the callback function to provide results if your function generates the gallery asynchronously, simply call it like this: `cb(items)`

For declarative syntax:

* `fix` function parameters:
  * `s` - string: caption, title, url
  * `isURL` - whether `s` is for the `url` property
* both `entry` and `image` are in the same document, which is remote by default.
* `entry` is the gallery item container so you can use short relative selectors for `image` and `caption` inside that container e.g. `"entry":".item", "image":"img", "caption":"span.description"`

```

**Comment by darkred** [comment]
Thanks a lot for explaining everything and for the improvement with the new commit!

**Comment by darkred** [comment]
I have one question:

in either syntax, when used on current page,
could it be possible, when hovering a thumb that is not the first one,
to show in the popup the full image of the **hovered thumb**, instead of the 1st in the page?

i.e. for function mode, something like an extra parameter: "startfrom": "node"

```json
{"d": "example",
 "e": "#image > a",
 "s": "gallery",
 "g": {
  "image": ".image > a",
  "startfrom": "node"
 }
}
```

and for declarative syntax, something like returning an array: `return [g, node]` in `"g"`?
```json
{"d": "example",
 "e": "#image > a",
 "s": "gallery",
 "g": "var g=[], r=/thumbs\\.example\\.com/g; while(m=r.exec(text)) g.push({url:m}); return [g, node]" 
}
```

**Comment by tophf** [comment]
`node` is not related to URLs so I don't see it being useful. I can add `"index"` property that can be a function in declarative mode or a number. In function mode it'll be a property on the returned value just like `title` is, e.g. `g.index = 2; return g`.

**Comment by tophf** [comment]
Added.

**Comment by darkred** [comment]
Thank you.
But, now, how can I make that `"index"` property, in either declarative or function mode, take the value that refers to the URL of the node that triggered the popup? Could you please give a simple example for both modes?
(excuse my ignorance, but I can't seem to think of a way to manage this.)

**Comment by tophf** [comment]
I would need to see the actual rule and the site but generally you would use the standard JS functions like indexOf and so on.

**Comment by darkred** [comment]
What about this example gallery?
http://www.twilightsite.com/fantasy/Old/Royo/Royo.html

(I've only managed to make these simple rules, one for each mode, and unfortunately the former is not even complete.)

```json
{"d": "twilightsite.com",
 "e": "td > a",
 "s": "gallery",
 "g": "var g=[], r=/fantasy\/old/g; /* ??? */ return g"
}
```

```json
{"d": "twilightsite.com",
 "e": "td > a",
 "s": "gallery",
 "g": {
  "image": "td > a"
 }
}

```

**Comment by tophf** [comment]
I've updated mpiv and now you can write it like this:

```json
{"d": "twilightsite.com",
 "e": "td > a:first-child",
 "s": "gallery",
 "g": "var g=[...document.querySelectorAll(rule.e)].map(_=>({url:_.href})); g.index=node.href; return g"
}
```

```json
{"d": "twilightsite.com",
 "e": "td > a:first-child",
 "s": "gallery",
 "g": {
  "image": "td > a:first-child",
  "index": "return node.href"
 }
}
```

**Comment by darkred** [comment]
Thanks so much, it works great!

**Comment by darkred** [comment]
I've noticed this issue:

STR:
(in a fresh Chrome 81 profile with only TM 4.10.6112 and latest version of script, 1.1.10 )

- open http://www.twilightsite.com/fantasy/Old/Royo/Royo.html
-add your first rule <sup>(I slightly changed `"e"` to not include the "back to start" link in the end)</sup>
```json
{"d": "twilightsite.com",
 "e": "tr:not(:nth-child(2)) > td > a:first-child",
 "s": "gallery",
 "g": "var g=[], r=/fantasy\/old/g; /* ??? */; return g"
}
```
- mouseover the first thumbnail, (the full image in displayed in popup).
Also, rightclick once (to activate zoom), notice that it works ok
- now move mouse away and click somewhere, then mouseover again on the first thumbnail, and mousewheel scroll down very quickly and/or multiple times e.g. to reach image 17: 
when the currently reached full image is displayed in the popup: try to rightclick once to activate zoom: notice that the zoom no longer works. If you rightclick the second time, the popup now closes. 
- From now on, if now you you click away and try to mouseover any image, the zoom no longer works, unless you reload the page.
- if the issue doesn't occur, clean browser cache and try again, the issue will surely occur.

**Comment by tophf** [comment]
Yeah, I can reproduce the bug.

**Comment by tophf** [comment]
Should be fixed now.

**Comment by darkred** [comment]
Yes, it's fixed, thank you! (and sorry for having the 2nd rule instead of the 1st.., corrected it).

There's one more thing, that occurs very often:
as you scroll down quickly, sometimes image displayed in the popup has the wrong ratio.
Could this be avoided?

Screenshot example [24/33]:
![Screenshot (1888)~](https://user-images.githubusercontent.com/723651/79144555-d4c70c80-7dc7-11ea-8ad6-3a8f2ef7eb55.jpg)

**Comment by tophf** [comment]
I've never encountered this so once I do I'll fix it.

**Comment by darkred** [comment]
I believe it helps recreating the issue if you clean the cache.
I tried it just now, and of my 4 tries scrolling down mousewheen, it occurred in 3 of them.

**Comment by tophf** [comment]
Should be fixed now.

**Comment by darkred** [comment]
Yes, it is. Thanks again!

**Comment by darkred** [comment]
Greetings

Currently, if the page initially loads, and the cursor is located over a thumbnail,
the popup is not displayed unless you slightly move the cursor over the thumbnail.
I'd like to make a suggestion please:
to add an option checkbox named: `Show popup when mouseover at page load`.

**Comment by tophf** [comment]
Sounds like something that would make sense being enabled by default. Try the master branch.

**Comment by darkred** [comment]
Thanks a lot for the quick response!

It works but I noticed the following:

- In a fresh Chrome profile with only TM/VM and the script
- open http://www.twilightsite.com/fantasy/Old/Royo/Royo.html
- mouseover the `Royo10.jpg` thumbnail (the popup will be displayed)
- now reload page (F5 or Ctrl+F5): notice that the cursor is initially not visible (and remains until you move it)

**Comment by darkred** [comment]
@tophf 
I didn't express the last step of the STP fully, sorry. Here:

> - now reload page (F5 or Ctrl+F5): notice that **the popup is not displayed for the above thumbnail** *(and the cursor is initially not visible (and remains hidden until you move it))*

The STR occurs consistently. 
I think it occurs for thumbnails (such as Royo10.jpg and Royo17.jpg), that when the popup displays the relevant full size image,
the popup covers the thumbnail, so the cursor is not visible.
Then, pressing F5 for some reason, causes the cursor to initially be hidden, and so there's effectively no hover event.

**Comment by darkred** [comment]
@tophf Maybe this issue is a Chrome browser "glitch" (but it happens in Firefox too), 
and it can't be fixed in the script ??

**Comment by tophf** [comment]
I didn't investigate it yet. Apparently there's a problem in the gallery mode.

**Comment by darkred** [comment]
I think I have caused confusion.. Sorry..

I reported [this problem](https://github.com/tophf/mpiv/issues/25#issuecomment-657712805) in this issue by mistake - I should have posted it in issue #23 instead.
This doesn't have to do with the gallery mode:
it occurs In a fresh Chrome profile with MPIV initial settings, 
in every page (i.e. without a "g" property in the rule) where the popup covers the thumbnail and you press F5/Ctrl+5 : 
e.g. https://www.google.com/search?tbm=isch&q=landscapes

**Comment by darkred** [comment]
One more thing to add:
with MPIV disabled, in all tests I tried, there hasn't been a case for me that the cursor becomes hidden after pressing F5/Ctrl+F5.
That's why I believe this problem has to do with the script and it's not a browser bug.

**Comment by tophf** [comment]
I'll disable this feature until I have time to investigate.

**Comment by darkred** [comment]
I took the liberty of making a separate issue for this feature, #34 *(and hid all my related comments in here)*.
I describe the issue there the best I can.

**Comment by darkred** [comment]
I was wondering, is it possible to combine current+remote page in the same gallery rule?
What I have in mind is gallery pages where the full size image can be retrieved, not from the same page's thumbnail element, 
but from the thumbnail's target remote page,
i.e. as you are in such a gallery, you mouseover the 1st thumbnail and you mousewheel/j/k/left/right arrow ,
the script to retrieve each next thumbnail's target remote page, get the full size image URL and display it as gallery?

Example gallery (SFW) -open in a new tab- 
https://www.imagefap.com/gallery.php?gid=9137691

The rule in the repo is: 

```json
{"d": "imagefap.com",
 "r": "imagefap\\.com/(image|photo)",
 "q": "[itemprop='contentUrl']"
}
```

Could that be changed to something like my non-working ("empty gallery") effort below?
If not, could you please add this functionality?

```json
{"d": "imagefap.com",
 "e": ".expp-container tbody > tr > td > a > img",
 "s": "gallery",
 "g": {
  "entry": ".image-wrapper",
  "image": "img"
 }
}
```

**Comment by tophf** [comment]
Yeah you can add properties to the `rule` object inside `s` function.

**Comment by darkred** [comment]
I'm glad the functionality is available!

Excuse me though, I'm trying this but it doesn't work:

```json
{"d": "imagefap.com",
 "e": ".expp-container tbody > tr > td > a > img",
 "g": "gallery",
 "s": "rule.q = '[itemprop='contentUrl']'"
}
```

As I see in TM/VM background's page when I mouseover a thumbnail, 
that the script tries to load xhr like this:
`https://www.imagefap.com/pictures/9137691/S.E.-CUPP-104/rule.q%20=%20'[itemprop='contentUrl']'`

What am I doing wrong?

**Comment by tophf** [comment]
`s` function must fulfill its main purpose and return a valid URL.

**Comment by darkred** [comment]
Ok.

So, I tried

```json
{"d": "imagefap.com",
 "e": ".expp-container tbody > tr > td > a > img",
 "g": "gallery",
 "s": "rule.q = '[itemprop=\"contentUrl\"]'; return doc.querySelector(rule.q).href;"
}
```
and I get `Uncaught ReferenceError: doc is not defined`
because you have told me that: `doc` (remote response as document) is undefined in `"s":"gallery"` mode.

**Comment by tophf** [comment]
`s` function runs in the current document, not in the remote one, so it doesn't have `doc`. The URL returned by `s` function in these cases should point to the remote page that will be fetched by MPIV and then it'll run `g` or `q` on the result as usual.

**Comment by tophf** [comment]
Also note, these rules should be added dynamically so if you gonna always have `g` on the rules then it will take precedence.

**Comment by tophf** [comment]
You can see examples in built-in rules. Although they use `Ruler.toggle`, which you can't use in your code, they still are helpful as an example.

**Comment by darkred** [comment]
Thank you very much for the detailed replies!

I came up to this:

```json
{"d": "imagefap.com",
 "e": ".expp-container tbody > tr > td > a",
 "g": "gallery",
 "s": "rule.q = '[itemprop=\"contentUrl\"]'; return node.href;"
}
```

which I think it would work ok. It loads the remote page, but never completes (the cursor keeps spinning).
I'm sorry but could you please try it with the example I gave: https://www.imagefap.com/gallery.php?gid=9137691 ?
I'm trying my best to make it , but unfortunately I can't. 😢

<details>
<summary>For reference, the working rule in the repo is:</summary>

```json
{"d": "imagefap.com",
 "r": "imagefap\\.com/(image|photo)",
 "q": "[itemprop='contentUrl']"
}
```
</details>

**Comment by tophf** [comment]
What I said above means your rule shouldn't have `g` or `q` properties initially. You should toggle them inside `s` function.

**Comment by darkred** [comment]
Thank you! Finally the rule below works ok on mouseover. 

There's just a small problem: `index` is always "undefined" no matter which thumbnail I hover, so it always starts from the 1st image.
And, for "s" I can't use `index: return node.href` instead of `index: node.href` because of the `return node.href` in the end.
How can I fix this?

```json
{"d": "imagefap.com",
 "r": "imagefap\\.com/(image|photo)",
 "s": "rule.g = {image: '.expp-container tbody > tr > td > a', index: node.href}; rule.q = '[itemprop=\"contentUrl\"]'; return node.href;"
}
```

**Comment by tophf** [comment]
When you specify a URL in `index` it must be one of those that the gallery contains so in your case I guess it's different.

You can define `g` separately and only set `rule.index` in your `s` either using a number or the final URL.

I'm not sure if defining `q` makes any difference with gallery, but I don't remember exactly.

**Comment by darkred** [comment]
> When you specify a URL in `index` it must be one of those that the gallery contains so in your case I guess it's different.

The gallery in my case contains thumbnails, and each full size image URL can only be retrieved by each thumbnail's target page. 
In general, the `index` property can only be a URL or a fixed number (e.g. `2`).
The `node.href` that I use, has `node`. which means "element that triggered popup".
Therefore `node.href` means the target URL of each thumbnail element. All these target URLs are contained in the current document.

So, what do you mean when saying *"it must be one of those that the gallery contains"* ?
With the word 'gallery', are you referring to the current document (with the thumbnails), or to each remote/target one?


&nbsp;


> You can define `g` separately and only set `rule.index` in your `s` either using a number or the final URL.

The target URLs are like this:

```
1st thumb: https://www.imagefap.com/photo/81959572/?pgid=&gid=9137691&page=0&idx=0
2nd thumb: https://www.imagefap.com/photo/81959572/?pgid=&gid=9137691&page=0&idx=1
3rd thumb: https://www.imagefap.com/photo/81959572/?pgid=&gid=9137691&page=0&idx=2
etc
```

so with a regex I could extract the index part (after `&idx=`).

And, if I understand you correctly, I tried replacing (added newlines for clarity) :

```json
 "s": "rule.g = {
	  	  image: '.expp-container tbody > tr > td > a', 
	  	  index: node.href
	    }; 
	  rule.q = '[itemprop=\"contentUrl\"]'; 
	  return node.href;"
```

with

```json
 "s": "rule.g = {image: '.expp-container tbody > tr > td > a'}; 
	   rule.index = /.+&idx=([0-9]+)/.exec(node.href)[1]; 
	   rule.q = '[itemprop=\"contentUrl\"]'; 
       return node.href;"
```

but it does't work: I'm getting `Uncaught TypeError: Cannot read property '1' of null`

**Comment by tophf** [comment]
* "gallery" in MPIV is a collection of full-sized images, not their thumbnails
* `rule.index` should be `rule.g.index`
* "Cannot read property '1' of null" means that your regexp didn't match anything e.g. you hovered some link that doesn't have `idx` in href. In modern browsers you can write `?.[1]` instead of `[1]`.

**Comment by darkred** [comment]
Ok, thank you.

So I came up to this:

```json
{"d": "imagefap.com",
 "e": ".expp-container tbody > tr > td > a",
 "s": "rule.g = {}; rule.g.image = '.expp-container tbody > tr > td > a'; rule.g.index = /.+&idx=([0-9]+)/.exec(node.href)?.[1]; rule.q = '[itemprop=\"contentUrl\"]'; return node.href"
}
```

which unfortunately doesn't work (`Empty gallery`).
But, as I see in logging (with Console open), all attributes in "s" get the expected values, and the `g.image` selector is valid 
*(`td` should change to `td[style^=\"width:180px\"]` to exclude profile images)*


P.S. Just to avoid any misunderstanding, the example page I gave https://www.imagefap.com/pictures/9137691/S.E.-CUPP-104 is non-porn of course.

**Comment by tophf** [comment]
Ah, so you want to build a virtual gallery from the links on the current page. You should probably use a gallery function to generate the list.

**Comment by darkred** [comment]
Ok, so shouldn't the following work ok? Again `empty gallery`

```json
{"d": "imagefap.com",
 "e": ".expp-container tbody > tr > td[style^=\"width:180px\"] > a",
 "s": "var g = [...document.querySelectorAll(rule.e)].map(_=>({url:_.href})); g.index = /.+&idx=([0-9]+)/.exec(node.href)?.[1]; rule.g=g; rule.q = '[itemprop=\"contentUrl\"]'; return node.href"
}
```

Is the `rule g=g` the wrong part?

**Comment by tophf** [comment]
You need to make `g` a function for MPIV so it'd be something like `rule.g = "var g=.......; return g"`

**Comment by darkred** [comment]
Finally it works ok:

```json
{"d": "imagefap.com",
 "e": ".expp-container tbody > tr > td[style^=\"width:180px\"] > a",
 "s": "gallery",
 "g": "var g = [...document.querySelectorAll(rule.e)].map(_=>({url:_.href})); g.index = node.href; return g",
 "q": "[itemprop=\"contentUrl\"]"
}
```

This conversation has been highly educational in Javascript, as always!
Thanks a lot for your help and time! 👍 🙂
