### ISSUE TITLE
fetlife support

### ISSUE THREAD

**Issue by ANaPhOrAX** [tophf/mpiv#26]
Hey, any chance of fetlife being supported? It was in the old one, but that code doesn't seem to work anymore (just tested that script, nothing happened).

**Comment by tophf** [comment]
I don't see a rule for `fetlife` in the code of the old MPIV. Generally I'm against adding embedding rules for such sites. Also this seems to be a member-only site so I don't know if the old mpiv still works there and I'm not interested in signing in to check that. If you can write a rule yourself I can add it to the optional rule installer in the config UI.

**Comment by tophf** [comment]
Try posting in the [feedback section](https://greasyfork.org/en/scripts/404-mouseover-popup-image-viewer/feedback) of the original MPIV, maybe someone will write a rule.
