### ISSUE TITLE
imgur.com Compatibility

### ISSUE THREAD

**Issue by Nzzyme** [tophf/mpiv#27]
Can you please check the compatibility with imgur.com

I have assigned the following:

Pop-up shows on: Ctrl

However, when I move mouse pointer over an imgur link and click 'Ctrl' key, the image does not pop out.

Example: https://i.imgur.com/60larfa.png

![image](https://user-images.githubusercontent.com/6959116/81502300-cbfc2480-92fa-11ea-9b9b-c960272359ba.png)

**Comment by tophf** [comment]
This is caused by github's restrictive CSP and I've fixed it in the master branch. Please test it by re-installing manually from https://github.com/tophf/mpiv/raw/master/script.user.js

**Comment by Nzzyme** [comment]
Thanks, works like a charm now.

**Comment by tophf** [comment]
Thanks for testing.
