### ISSUE TITLE
Rotate Image [Suggestion]

### ISSUE THREAD

**Issue by Nzzyme** [tophf/mpiv#28]
Hi,

I was wondering if it is possible to include a rotate option in your script such that after the image pops-out, when we press on the arrow buttons of the keyboard (or icons on the popped-up image), the image should rotate as follows:

Left arrow: rotate image left by 90 degrees
Right arrow: rotate image right by 90 degrees

Additional key shortcuts can be added to rotate image horizontally & vertically.

Thanks

**Comment by tophf** [comment]
Arrow keys left/right are used for navigation in the gallery mode. Using up/down would be weird for this. Icons might be handy but that's a lot of work so I've added <kbd>L</kbd> (rotate left) and <kbd>R</kbd> (rotate right). You can test it by reinstalling from the [master branch](https://github.com/tophf/mpiv/raw/master/script.user.js).

**Comment by Nzzyme** [comment]
I updated the script and observed that I am no longer able to pop-up any image after hovering the mouse pointer over an image and pressing the Ctrl key.

Settings Screenshot:
https://i.imgur.com/I8MK0LQ.png

**Comment by tophf** [comment]
Should be fixed now. Reinstall it again.

**Comment by Nzzyme** [comment]
Ok, it works now. Thanks
