### ISSUE TITLE
Enhancement request: ability to blacklist sites from menu

### ISSUE THREAD

**Issue by bermudalocket** [tophf/mpiv#29]
First of all, thank you for forking, updating, and maintaining this project. I used Imagus religiously on Firefox, and it was the one extension for which I couldn't find an alternative for Safari 13+. Your fork has allowed me to switch back to Safari, so I'm incredibly thankful to you for that.

I do have one suggestion I'd like to see implemented: a quick-and-easy blacklist. I've found myself wishing for this feature many times over the last few weeks. There are some websites, such as Apple's App Store Connect, on which this script is more of an annoyance than a blessing. I know I could create a cascading rule to prevent certain elements from presenting a popup but that's time-consuming and not necessarily user-friendly for some.

I did try to implement this myself before I opened this issue. I am a developer but I'm not well-versed in Javascript, so ~3500 lines proved to be a little too much for me to digest in a reasonable amount of time.

Here's a dummy screenshot showing exactly what I mean by an easily-accessible blacklist button:

<img width="340" alt="CleanShot 2020-05-23 at 17 25 50@2x" src="https://user-images.githubusercontent.com/30004636/82740858-93a50f00-9d1a-11ea-921c-169728bddc5f.png">

**Comment by tophf** [comment]
This is a feature that belongs to the userscript manager and it's already implemented. In Tampermonkey you can click `+` then exclude the site. In Violentmonkey (and other managers) you can add an exclusion in the editor.
