### ISSUE TITLE
how to configure? (userscript manager toolbar icon -> User Script Commands -> MPIV: configure)

### ISSUE THREAD

**Issue by gitgetgot** [tophf/mpiv#32]
Hi,
I know, this seems to be an odd question,

but I can not understand/put in practice the "userscript manager toolbar icon -> User Script Commands -> MPIV: configure".

I'm using FF 78.0.2 (64-bit) on Mac OSX and when I click the toolbar icon, I see this:
<img width="324" alt="Bildschirmfoto 2020-07-27 um 18 31 34" src="https://user-images.githubusercontent.com/974980/88567527-e90ddd00-d037-11ea-956e-65447653bac1.png">

No Idea what comes next, to see the [configuration window](https://camo.githubusercontent.com/5a9207e295424736e3898390ac65c91b432c6046/68747470733a2f2f692e696d6775722e636f6d2f696c4a643078642e706e67).

Clicking on MPIV only de-/activates the script or opens it for editing.

Any advice?

Thank you!

**Comment by tophf** [comment]
It should be displayed there, right below the userscript. Check Violentmonkey advanced settings - maybe you have a custom CSS that hides the menu item.

**Comment by tophf** [comment]
Try updating Violentmonkey too. You seem to be using a really old version, judging by the screenshot.

**Comment by gitgetgot** [comment]
> It should be displayed there, right below the userscript. Check Violentmonkey advanced settings - maybe you have a custom CSS that hides the menu item.

Thank you!
Resetting the Editors Custom options did the Trick! VM did add some more lines to it. Nice!

<img width="504" alt="Bildschirmfoto 2020-07-27 um 19 32 21" src="https://user-images.githubusercontent.com/974980/88572709-eb743500-d03f-11ea-8e89-b21072c89aad.png">


Now it is showing the important stuff:
<img width="321" alt="Bildschirmfoto 2020-07-27 um 19 30 10" src="https://user-images.githubusercontent.com/974980/88572596-b1a32e80-d03f-11ea-8f89-4b6ac91f0a52.png">




> Try updating Violentmonkey too. You seem to be using a really old version, judging by the screenshot.

I'm using 
Version
2.12.7
Last Updated
14 February 2020

And after clicking the Update Buttons, it says "no updates available". 

Maybe I just use a boring FF theme :-)

Thank you both again! (Especially, it turned out, it was a VM problem, not a script problem!)
