### ISSUE TITLE
Auto-activate on hovered image at `load` event

### ISSUE THREAD

**Issue by darkred** [tophf/mpiv#34]
*Split from https://github.com/tophf/mpiv/issues/25#issuecomment-657712805 (because I had posted it in the wrong issue)*

---

My suggestion:

> Currently, if the page initially loads, and the cursor is located over a thumbnail,
> the popup is not displayed unless you slightly move the cursor over the thumbnail.
> I'd like to make a suggestion please:
> to add an option checkbox named: Show popup when mouseover at page load.

---

@tophf kindly implemented this in https://github.com/tophf/mpiv/commit/a7cb177d887c119a9fde950692bd827b4ec9bd47 with the comment:

> Sounds like something that would make sense being enabled by default. Try the master branch.

I tested it and reported the following issue (see below), and tophf reverted the commit via https://github.com/tophf/mpiv/commit/3fccd8f9cf6436cc03b5468fcacf3823bf651608 until he's able to investigate.

---

It **currently works ok** if, while you are in an empty tab (or an irrelevant page, e.g. https://www.google.com/ ),
you move the mouse where you expect the thumbnail to be located after page load,
and focus on the address bar (via Ctrl+L/F6) and enter the test URL(see below) to load the page: 
**the popup will appear ok on page load**.

**The issue**:
it **doesn't work** when, while you are in a page,
you move the mouse on a thumbnail to activate the popup, and then keep the mouse still (either keeping the popup open, or deactivate it via click, it doesn't matter), and you just reload the page (F5/Ctrl+F5): 
**there will be no popup on page load**.

Test URL: http://www.twilightsite.com/fantasy/Old/Royo/Royo.html

**Comment by darkred** [comment]
@tophf 
I've been searching in StackOverflow regarding the [issue](https://github.com/tophf/mpiv/issues/34#issue-680153188-permalink:~:text=The%20issue%3A,be%20no%20popup%20on%20page%20load.) I reported above
and in various answers/comments (see below) it says that it's a "**browser limitation**" :
**as long as the user doesn't move the mouse after the page reload is completed, no `mouseover` event is fired** 

<details>
<summary>StackOverflow answers/comments</summary>

- [Mouse positioned over image when page loads doesn't fire onmouseover event (answer)](https://stackoverflow.com/a/3651199), 

  >  I do not believe that this is possible, since the browser determines the mouseover event based on mousemoves

- [Is mouse over element on page refresh without moving it? (comment)](https://stackoverflow.com/questions/40706774/is-mouse-over-element-on-page-refresh-without-moving-it#comment68642116_40706774), 

  > I think your expectation is based on a wrong concept. HOVER means move the mouse over.... Since you are not moving the mouse after the refresh is completed, no HOVER event is fired


- [How to get the mouse position without events (without moving the mouse)? (comment)](https://stackoverflow.com/a/2601119)

  > No, it's not possible.

</details>

Therefore maybe implementing what I reported is not possible?
If yes, could you please just re-add your https://github.com/tophf/mpiv/commit/a7cb177d887c119a9fde950692bd827b4ec9bd47 commit, and close this issue?

**Comment by darkred** [comment]
Hi @tophf 
Have you found any time to investigate this issue?
If not, maybe could you please give any estimation on when you could check? Could it be several months later, next year?
I'd just like to know if you are still busy, but the last thing I'd want is to bother you.

**Comment by tophf** [comment]
I have no idea. Sometimes I don't code for years.

**Comment by darkred** [comment]
Ok, thanks for replying.

**Comment by darkred** [comment]
> Sometimes I don't code for years.

I hope your reply wasn't ironic, but I can only say: sorry for bothering you with bumping the thread. I've closed the issue.

**Comment by tophf** [comment]
Might be because of https://crbug.com/307375

**Comment by darkred** [comment]
Thank you for finding that chromium bug 👍
So, this is a Chrome issue. _(I confirm what's described in that bug, that in Firefox it never occurs)_. 
Let's hope that chromium bug will eventually gets fixed.

**Comment by tophf** [comment]
I've just removed such auto-activation in YT-hover because it was driving me mad for quite a while when I open a page and the preview activated for irrelevant random stuff which happened to load under the mouse cursor.

**Comment by darkred** [comment]
The `:hover` CSS rule on page load is already working ok in Firefox.
It's not working in Chrome (your linked chromium bug).

So, could I ask you please to re-add your https://github.com/tophf/mpiv/commit/a7cb177d887c119a9fde950692bd827b4ec9bd47 commit, controlled via a configuration setting, disabled by default ?
(with a note in the wiki that this feature is currently meant for Firefox users).

Having this feature in MPIV would mean the world to me ! I find myself everyday in need for it.

**Comment by tophf** [comment]
Along with an option that'd too much code for something that I actively dislike... Do you use Firefox normally?

**Comment by darkred** [comment]
Yes, I use it everyday.

**Comment by tophf** [comment]
So if I understand correctly, there's no problem in Firefox? In which case why do you care about the option in Chrome?

**Comment by darkred** [comment]
With https://github.com/tophf/mpiv/issues/25#issuecomment-657712805
I had made this feature request to you: to auto-activate on hovered image at `load` event .

You implemented it with commit https://github.com/tophf/mpiv/commit/a7cb177d887c119a9fde950692bd827b4ec9bd47

It worked ok in Firefox, but not in Chrome due to your linked chromium bug.
That's why you had to revert it with this commit https://github.com/tophf/mpiv/commit/3fccd8f9cf6436cc03b5468fcacf3823bf651608

What I'm asking now is to re-add the feature, i.e. re-add your initial commit https://github.com/tophf/mpiv/commit/a7cb177d887c119a9fde950692bd827b4ec9bd47 , 
controlled via a configuration setting, that would be disabled by default.

This way, enabling it Firefox, it work ok.
Enabling it in Chrome it won't make any difference until that chromium bug gets fixed.

**Comment by tophf** [comment]
Your earlier statement "already working ok in Firefox" confused me. I see what you mean now but I don't like to add features that I actively dislike unless there's a lot of people using it in other scripts/extensions.

**Comment by darkred** [comment]
Sorry for not expressing it right.

But, I'd still would like to ask you to consider re-adding this feature, as a personal favor.
It's something I find myself needing it all the time.
I know it sounds strange, but it's not exaggeration when I said that having this feature would mean the world to me.
I'd be utterly in debt to you if you added it.

**Comment by tophf** [comment]
You can add it in your own fork.

**Comment by darkred** [comment]
Unfortunately I can't implement it myself. I'm nowhere near your experience and knowledge.

**Comment by darkred** [comment]
@tophf 
I underestimated myself as usual..

I made a PR #56. 
I hope you agree to merge 🙂

**Comment by darkred** [comment]
And, I feel the need to clarify something:

> You can add it in your own fork.

Yes, but it's not like I want you use your project as a starting point for my own idea. It's only that one feature.

I'm not experienced or capable enough to contribute anything particularly improved or advanced or different in the script code.
My only "contributions" in the repo so far are just feature requests, reporting issues and only few simplistic PRs...

I totally admire your work in the MPIV rewrite. 
It was good in its initial form but has become *way better* I could ever wish for.
And (as mentioned by another user), if you provide a way to donate (paypal,patreon,etc), I'll be the first to do so.

---

I hope that when/if that chromium bug https://crbug.com/307375 gets eventually fixed (it's already 7.5 years later),
so that Chrome becomes behaves correctly, like Firefox does on this matter, you'll agree to merge my PR.

**Comment by darkred** [comment]
The reason I want this feature so much, 
is that, my personal workflow is that I open pages via clicking "`+` / New Tab" in the browser,
and type some characters in the address bar and press Enter. I don't move the mouse until the page loads, rarely if ever.

On page load:
- in Firefox, the hover effect is seen ok. 
- in Chrome, the hover effect is not seen, until the mouse is moved from its initial position.
Additionally, the cursor itself gets hidden by MPIV on hover -but there's no popup-, until you move mouse a bit.
This fact, that the cursor becomes hidden by MPIV but there's no popup,
constantly gives me the wrong impression that there's something wrong with MPIV itself, or my custom rule.

**Comment by darkred** [comment]
@tophf That chromium bug [crbug.com/307375](https://crbug.com/307375) is finally fixed with Chrome 130 stable!

<details>
<summary>Screenshot:</summary>

![](https://github.com/user-attachments/assets/fa5cfdc0-1f0a-4fed-9147-d9b1a829c34c)

</details>

So, I thought to try again adding the auto-activate on hovered image at load event in Chrome.
I've tried testing your commit https://github.com/tophf/mpiv/commit/a7cb177d887c119a9fde950692bd827b4ec9bd47 from https://github.com/tophf/mpiv/issues/25#issuecomment-657719278 but unfortunately it doesn't auto-activate.
I've also tried your script from https://github.com/tophf/mpiv/pull/56#issuecomment-831357361 (removing the enclosing `if (!/chrom/i.test(navigator.userAgent))` ) but it still doesn't auto-activate.

Maybe you'd like to now reconsider adding this feature as an option? I'd be grateful if you would.

**Comment by tophf** [comment]
If that commit (a7cb177) doesn't work it can only mean there's yet another bug in Chrome and I don't see how it can be circumvented.

**Comment by darkred** [comment]
First of all, I found that the script works fine with Chrome 130 as it is with built-in rules. So, no need to add that commit https://github.com/tophf/mpiv/commit/a7cb177d887c119a9fde950692bd827b4ec9bd47 .

For example, with built-in rules, if you point mouse on a thumbnail in e.g. https://www.metal-archives.com/bands/Iron_Maiden/25
or in my first post's test URL http://www.twilightsite.com/fantasy/Old/Royo/Royo.html
and reload page, then the popup is displayed ok after you reload the page (F5).

*I was only testing only with xkdc.com pages (of the chromium bug) and with the above test URL that gallery custom rule, that's why I thought that it doesn't work.*

---

And yes, I found it, it's indeed some Chrome bug that still exists:
It only occurs when you use a custom gallery rule, e.g. the one from https://github.com/tophf/mpiv/issues/25#issuecomment-607609675, that is:

```json
{"d": "[twilightsite.com](http://twilightsite.com/)",
 "e": "td > a:first-child",
 "s": "gallery",
 "g": {
  "image": "td > a:first-child",
  "index": "return node.href"
 }
}
```
with URL http://www.twilightsite.com/fantasy/Old/Royo/Royo.html :
load the page (using that custom rule) and point mouse to a thumb so that the popup appears.
Now, if you reload the page while the popup is visible, then (after reload) the cursor becomes hidden and it also remains hidden on subsequent page reloads (F5). The cursor only reappears when mouse is moved.


This doesn't occur with Firefox.

**Comment by darkred** [comment]
In other words, the script works fine. I'll report here when/if that other Chrome bug is finally fixed by Google.
