### ISSUE TITLE
`Run in image tabs` not working

### ISSUE THREAD

**Issue by darkred** [tophf/mpiv#35]
I've noticed in the script (in both Tampermonkey/Violentmonkey in Chrome/Firefox)
that when I enable `Run in image tabs` and open a large image in a new tab (see below), there's no popup on mouseover.
There's no error in Console.

Test image URL (open in new tab)
https://images.hdqwalls.com/wallpapers/beautiful-landscapes-of-new-zealand-4k-xn.jpg

Thank you

**Comment by tophf** [comment]
Fixed in 621487d3

**Comment by darkred** [comment]
Thank you!
