### ISSUE TITLE
instagram not working anymore?

### ISSUE THREAD

**Issue by ANaPhOrAX** [tophf/mpiv#39]
It just stopped working for me. I'm getting "Unexpected token < in JSON at position 0"

**Comment by tophf** [comment]
Works for me. Any details, URL?

**Comment by tophf** [comment]
Maybe you have a custom rule? Open `MPIV configure` and remove it.

**Comment by ANaPhOrAX** [comment]
It's been working again since I posted. I have no idea why it happened, because I definitely don't have any custom rules. Very strange. Maybe a bad interaction with another browser addon? An ad blocker? Maybe I had my vpn running and that caused it? (dont believe I did, but it's been almost 3 weeks now so idno now)
