### ISSUE TITLE
doesn't seem to be working on google atm

### ISSUE THREAD

**Issue by ANaPhOrAX** [tophf/mpiv#4]
is it just me or does it not work on google images atm?

seems fine on other sites.. but google images - nope.

site question: is it possible for me to disable the fade-in effect somehow? the old mpiv didn't have that, and I really don't like it.

edit: and the drop shadow? any way of disabling that as well?

**Comment by tophf** [comment]
1. The images should be shown in the updated version.
2. To disable the animation add `#mpiv-popup.mpiv-show { animation: none; box-shadow: none !important }` in "MPIV configure" dialog's Custom CSS section, which can be invoked from the Tampermonkey/Violentmonkey menu. See the [original site](https://w9p.co/userscripts/mpiv/css.html) for more info about customizing CSS, it's still mostly the same here.
