### ISSUE TITLE
Support for redgifs.com (NSFW)

### ISSUE THREAD

**Issue by mortadela1410** [tophf/mpiv#40]
Hi! Could you add support or create a rule for redgifs.com pretty please? It's used for movies and gifs on NSFW subreddits. It's somewhat similar to Gfycat, I've tried to do it myself, but I just can't wrap my head around it.

Thank you very much.

**Comment by tophf** [comment]
This seems to work:
```json
{
 "d": "reddit.com",
 "e": "[data-href-url^='https://redgifs.com/']",
 "q": "source[type='video/webm']"
}
```
