### ISSUE TITLE
Suggestion: a way for getting larger images in Instagram: 1440p instead of 1080p

### ISSUE THREAD

**Issue by darkred** [tophf/mpiv#41]
Greetings

I'd like to suggest adding to MPIV a way to retrieve larger images in Instagram: 1440p instead of 1080p
(the quality of the 1440px images is of noticeably better quality when compared to the 1080px images. It's not upscaling).

&nbsp;

---

Image Max URL, a [userscript](https://greasyfork.org/en/scripts/36662-image-max-url/) / [site](https://qsniyg.github.io/maxurl/) / browser extension, 
-among other things- manages to fetch from Instagram 1440p images instead of 1080p .

I checked its [code](https://greasyfork.org/en/scripts/36662-image-max-url/code) and [rules](https://cdn.jsdelivr.net/gh/qsniyg/maxurl@4ee74abe7a813c799ecc35fc5f6bb7d10a4f2a55/build/rules.js) and found how it's done
(the *trick* is sending xhr with a **modified User-Agent**, a hi-res instagram Android app one):

e.g. for `https://www.instagram.com/p/CIoSKljseUZ/`
- it gets the `Media ID` of the image, (probably without using the API,as I see in Network devtools)
*(we could get it as currently, via appending:`?__a=1` in the URL, i.e. `https://www.instagram.com/p/CIoSKljseUZ/?__a=1` 
and then `JSON.parse(text).graphql.shortcode_media`*.
In this case it's: `2461297088717251865`
- then send a GET request to `https://i.instagram.com/api/v1/media/{Media ID}/info/`
in this case `https://i.instagram.com/api/v1/media/2461297088717251865/info/`
using the following headers (basically just the User-Agent):

    ```javascript
		var headers = {
			"User-Agent": "Instagram 146.0.0.27.125 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G930F; herolte; samsungexynos8890; en_US)",
			"X-IG-Capabilities": "36oD",
			"Accept": "*/*",
			"Accept-Language": "en-US,en;q=0.8"
		};
    ```

   and the target 1440x1800 image is located in the retrieved JSON at:
`JSON.parse(text).items[0].image_versions2.candidates[0].url`

---

&nbsp;

Do you think it's worth adding this to MPIV, @tophf ?
The script I mention is unfortunately overly complicated, and takes too long each time to retrieve the larger IG image.
I'd definitely prefer to just implement its way to MPIV, than using it for that.

**Comment by tophf** [comment]
I would need a sample URL on which I would run upscale detection because instagram shouldn't have those big images according to their [documentation](https://help.instagram.com/1631821640426723).

**Comment by darkred** [comment]
On closer look/zoom, I think you are probably right that it's indeed upscaling...

Image comparisons :

https://www.instagram.com/p/CIoSKljseUZ/ (the URL example I gave above)
[1080p](https://user-images.githubusercontent.com/723651/101941784-24790480-3bf1-11eb-95bb-169cdc3430b1.jpg) vs [1440p](https://user-images.githubusercontent.com/723651/101941792-280c8b80-3bf1-11eb-9441-b47ece2271a8.jpg)

or https://www.instagram.com/p/CHVmYuGsxVA/
[1080p](https://user-images.githubusercontent.com/723651/101942558-66567a80-3bf2-11eb-8c4e-b98658cec3c7.jpg) vs [1440p](https://user-images.githubusercontent.com/723651/101942564-68b8d480-3bf2-11eb-941e-6d9b0e3b3b23.jpg)


or https://www.instagram.com/p/CILr9InsG75/
[1080p](https://user-images.githubusercontent.com/723651/101942573-6bb3c500-3bf2-11eb-8300-c86959c9b1f1.jpg) vs [1440p](https://user-images.githubusercontent.com/723651/101942581-6d7d8880-3bf2-11eb-8f33-3a579aa1cb3d.jpg)

---

To replicate yourself (the URLs alone don't work): 

- in a fresh Firefox profile (where it has a JSON viewer built-it)
just append `?__a=1` to each example URL, load it and click to open the relevant 1080p image URL,
- then use the `Media ID` and load for each one: `https://i.instagram.com/api/v1/media/{Media ID}/info/` and click to open the relevant 1440p image URL.

**Comment by tophf** [comment]
The level of detail is almost the same and in most parts 1440 looks like a sharpened upscale of 1080. Some parts look genuinely more detailed (like the football goal mesh) but the compression quality of 1440 is much worse and I see the blocky structure clearly. So, not sure this is worth the added complexity...

**Comment by darkred** [comment]
I agree with you.
Thanks for your time.
