### ISSUE TITLE
imgcredit

### ISSUE THREAD

**Issue by theaulddubliner** [tophf/mpiv#44]
Is this the right place to post site issues?

imgcredit.xyz is not working.

Thumb: http://s5.imgcredit.xyz/2021/01/25/54e62dfb02dc2fa305d594cd035ae77a.md.jpg

Full: http://imgcredit.xyz/image/diH67

**Comment by tophf** [comment]
```
{"r": "(//\\w+\\.imgcredit\\.xyz/\\d[\\w/]+)\\.md(.+)",
 "s": [
  "https:$1$2",
  "https:$1.png"
 ],
 "u": "imgcredit.xyz"
}
```
You can also post in [discussions](https://github.com/tophf/mpiv/discussions) so that it becomes a place where people share the rules, which will be then either integrated in the script or posted in our Wiki.

**Comment by theaulddubliner** [comment]
Thanks for that.
