### ISSUE TITLE
Blob images dereferenced after closing the popup

### ISSUE THREAD

**Issue by syfluqs** [tophf/mpiv#49]
I have observed this issue particularly on Whatsapp Web, where the images sent in chat are referenced by the browser as blob images. Upon opening and closing the image popup, whatsapp web app cannot find the image because the blob URL gets dereferenced/revoked by the following code in ```script.user.js``` under ```Popup.destroy``` method from line 1102.

``` javascript
if (!ai.lazyUnload) {
  if (p.src.startsWith('blob:'))
    URL.revokeObjectURL(p.src);
}
```
Because the Blob Url object gets revoked after the popup gets destroyed, whatsapp web shows a blurred placeholder image.

I couldn't understand the utility of above piece of code. 
So I tried commenting it out and it worked as expected, I could open the images as popup and after closing them, the whatsapp webapp could still show the images as usual.

**Comment by tophf** [comment]
Should be fixed in the new version. I didn't test it though...
