### ISSUE TITLE
ReferenceError: GM_getValue is not defined

### ISSUE THREAD

**Issue by IzzySoft** [tophf/mpiv#51]
I'm just trying to get MPIV running on the latest Waterfox G3 (which if I understand correctly, this 3rd gen Waterfox is based on Firefox 78). Nothing shows up – except in the console:

```
Script error in [Greasemonkey script https://github.com/tophf/Mouseover Popup Image Viewer; version 1.1.21]:
ReferenceError: GM_getValue is not defined
```

Just for comparison: Other userscripts work, also with `GM_getValue` (as far as I could see, those I tried are using PolyFill to map those calls, and then use `GM.getValue` instead).

Any ideas what I could try?

**Comment by tophf** [comment]
Generally I pretend that GreaseMonkey4 doesn't exist, just like it pretends that thousands of old scripts don't matter, but I can try making MPIV compatible.

**Comment by IzzySoft** [comment]
Thanks a lot! I'm using GM for … I don't remember how many years now, so it's probably "habit" that I still use it. As a user, I saw no reason to switch. But as a script writer, I was cursing quite a lot when they changed `GM_getValue` to a premise. I'm not an experienced JS "programmer", and rather use the "simple procedural approach" to work around little annoyances here and there. Especially this change made it very hard on me to work with "stored configs". But as it's called `GM*` I never got the idea other engines would handle it differently – which is why I was pretty surprised with this issue…

Thanks once more – works fine now!
