### ISSUE TITLE
Issue since few days/weeks

### ISSUE THREAD

**Issue by mikhoul** [tophf/mpiv#54]
I've seen an issue since few days/weeks, at first I was just thinking it was some unsupported pictures but I realized it is a new issue.

When I hover certains images with CTRL (to force MPIV) the popup show up quickly and disappear, look at the screncast:

 http://screencast-o-matic.com/watch/crfoDrVn53h
 
 
 I tried to open the console to see if something wrong happen in the background but as soon I open the console everything work fine strangely, again look at the screnncast when the console (F12) is open for the tab:
 
 http://screencast-o-matic.com/watch/crfoDUVn5Z2
 
 Here's the URL of my testL: https://www.newbalance.ca/en_ca/pd/new-balance-577/MW577.html
 
 But the issue happen on various sites/images, like on Google Image on the search results page some images are working some others just flicker unless I open the Devtools (F12).
 
Before it was working fine,
 
 
**Note:**  I use latest Brave with Windows and Tampermonkey.
 
 
 Regards :octocat:

**Comment by tophf** [comment]
Works for me in Chrome + Tampermonkey. Which version of the script are you using? Try the latest one [from github](https://github.com/tophf/mpiv/raw/master/script.user.js).

**Comment by mikhoul** [comment]
It was  1.2.3  but same thing happen with  1.2.4 🤔

Could you try on your side with Brave ?

**Comment by tophf** [comment]
Works in Brave too so I guess it might be a conflict with another extension or a userscript you have.

**Comment by mikhoul** [comment]
> Works in Brave too so I guess it might be a conflict with another extension or a userscript you have.

Thanks a lot for the testing, that's what I fear... a conflict with another extension.

I use over 50 extension but I will find which one is nonfactual even if it will be long to test..  :stuck_out_tongue:

**Comment by tophf** [comment]
Maybe it'd be faster for you to install older version of MPIV and see which one works. This would mean the bug is on my side.

**Comment by tophf** [comment]
Another user reported it. The problem occurs when holding the key for a long time instead of pressing it quickly as you would normally press any key. Should be fixed in 1.2.5.

**Comment by mikhoul** [comment]
Latest version 1.2.5 seem to have fixed the issue, I can use it like before.    👍

Thanks for the quick fix ! :octocat:
