### ISSUE TITLE
On-click settings toggle (Somehow)

### ISSUE THREAD

**Issue by malcomxxx** [tophf/mpiv#55]
I love this script. I donated to tampermonkey but I realize it should have been to you since this is the script I use the most!!
Question: I managed to implement a menu accelerator hotkey to the Config Panel, but still I'm wondering is there a faster way to quickly change the popup setting from auto to context (Which I am constantly toggling) without going though all the clicks. Any kind of one-click solution would be perfect - Keyboard shortcut, button, console cmd bound to a macro, ANYTHING!! Any suggestions?
Thank You in Advance For Your Time.

**Comment by tophf** [comment]
I can't imagine the use for such a toggle so I need a more detailed explanation of the benefits or why you need it.

**Comment by malcomxxx** [comment]
As you know when fast browsing many sites with many open tabs enlarged image popups can be very hindering depending on the makeup of the site. That's why MPIV Configuration was invented. But the long and the short of it is I am lazy and easily annoyed. MPIV has the basically all of the features I loved on firefox with an extension called Thumbnail Viewer Plus. Almost all but one big one. A toolbar button to quickly turn Zooming off.
![Toolbar Menu   Thumbnail Zoom Plus Full_cr_cr](https://user-images.githubusercontent.com/4473220/115497606-97def280-a231-11eb-88b8-896e9de950fb.jpg)
![thumbnail-zoom-plus_850492_full](https://user-images.githubusercontent.com/4473220/115497747-dffe1500-a231-11eb-99d4-3fc4676c6f93.png)
I'm trying to find a way to macro a key on my keyboard for quick quick action.
![84309378-b03da580-ab68-11ea-9d20-64ed623a32a7](https://user-images.githubusercontent.com/4473220/115497900-23f11a00-a232-11eb-8cdb-cd0d2a6dd7d4.png)

**Comment by malcomxxx** [comment]
As you know when fast browsing many sites with many open tabs enlarged image popups can be very hindering depending on the makeup of the site. That's why MPIV Configuration was invented. But the long and the short of it is I am lazy and easily annoyed. MPIV has the basically all of the features I loved on firefox with an extension called Thumbnail Viewer Plus. Almost all but one big one. A toolbar button to quickly turn Zooming off.

________________________________

**Comment by tophf** [comment]
I've added an option in the config to show the auto-start switch in the usermanager menu:

![image](https://user-images.githubusercontent.com/1310400/115505245-cdabc780-a281-11eb-97c1-e7597bbd6f32.png)

**Comment by tophf** [comment]
To test it, install https://github.com/tophf/mpiv/raw/master/script.user.js

**Comment by malcomxxx** [comment]
Man you are fast! Thank a lot. I will be donating as soon as I figure out how!
