### ISSUE TITLE
A few requests/issues

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#7]
Firstly, thanks very much for your work continuing work on this useful script.

Some requests/notes:

1) The number one feature I've always wished the original MPIV had is a "fit" scaling option where larger AND smaller images are fit to the viewport size. Currently, you can choose "0" scale to scale larger images down, or you can choose "Zoom Automatically" and "0" to get smaller images to fit to the viewport automatically, but then larger images are already zoomed in by default (I assume they get bumped to the "1" scale factor).

2) I'm not sure how easy this is to fix, but images on Reddit (old.reddit.com) never worked with MPIV, they all have an "expand" button which, when clicked, displays the image on the page.

3) An option to turn off the drop shadow would be nice; I tried doing it via CSS but it appears it isn't using the 'box-shadow' property to do it.

**Comment by tophf** [comment]
Re fitting, I guess I never really understood "custom scale factors", it's absolutely user-unfriendly so I'll probably rework this aspect entirely.

Re reddit, I'm not using it that much so you'll have to walk me through the process, give an example URL, etc.

To disable the shadow see https://github.com/tophf/mpiv/issues/4#issuecomment-581745422

**Comment by Ryujinra** [comment]
I agree that the custom scale factors probably need work; I have found it useful to generate a progression of step sizes such that zooming becomes increasingly more granular the further you zoom in, but there is probably a more organic way of accomplishing this same effect.

For reddit, visit [old.reddit.com/r/pics](https://old.reddit.com/r/pics); if you hover over the link for any title that ends in `(i.redd.it)` you'll see that nothing happens (indeed, the link itself redirects you to the thread and does not point directly to the image link. However, if you click the little "play" button next to the thumbnail, the full image is expanded and embedded in the page. The direct link to the image is in a "data-url" field in the parent div for the post.

Note that even after expanding the image, your rework of mpiv seems to have trouble dealing with the embedded image, whereas the original mpiv does not. If you hover over the expanded image, it attempts to open the popup, but the zoomed image doesn't load and the tooltip gives an `undefined` error.

**Comment by tophf** [comment]
I've updated both the built-in rules so you can copypaste the new code manually for now or force an update in the userscript manager. I'll bump the version later after reworking the zoom option.

The rule I've added is only for the thumbnail as it seems a much more natural hover target:

```js
{"d": "reddit.com",
 "e": "[data-url] img[src*='thumb']",
 "s": "let el=node.closest('[data-url]'); return el && el.dataset.url || ''"
}
```

**Comment by Ryujinra** [comment]
Great; on a second look, the rule should probably be further restricted by checking the field `data-domain=i.redd.it` (or alternatively use the `media-preview-content` element like the logic above instead of `data-url`, though I think the former is a better strategy); otherwise, it will try to zoom in on the thumbnails for website links and other non-image links it can't load, which will fail.

**Comment by tophf** [comment]
I would need to see such an example first.

**Comment by Ryujinra** [comment]
Visit [old.reddit.com/r/politics](https://old.reddit.com/r/politics). Hover over the thumbnail for any news link on the page, you'll see that with your rule, mpiv will try (and fail) to zoom the thumbnails. These thumbnails are just previews of the content from the actual webpage, mpiv shouldn't try to zoom them because they are not thumbnails of image links. If you check the `data-url` field, you'll see it doesn't contain the link to an image, but a link to a webpage. We can avoid this by just checking the `data-domain` link is equal to `i.redd.it`, so we know the data-url for the post represents an image we are interested in zooming.

**Comment by tophf** [comment]
Thanks. I've added the condition into data-url.

**Comment by tophf** [comment]
I've reworked the config UI and the way scaling works internally, also added a fit-to-window option. It's in the master branch now. Not sure it works correctly in all cases though as there are just too many options and their combinations that I never used.

**Comment by Ryujinra** [comment]
I tried out "fit to window" but it doesn't seem to do anything differently than before, if you had `0*` as your first zoom option. Originally, if you had `0*` as your first option, it would always fit smaller images to the window as the first zoom step, and larger images were already scaled down to the window size on the initial popup. 

The feature I thought would be really convenient was an option to have the smaller images fit to the window on the _initial_ popup, just like how larger images are automatically fit to the initial popup window, _without_ putting you into "zoom" mode automatically (which prevents you from closing the popup by moving the cursor alone).

Even if you set zoom to "Automatically" and "fit to window", there still seems to be a bug with this option, because smaller images are automatically zoomed slightly beyond the viewport, and larger images are just zoomed to 100% of the original size.

**Comment by tophf** [comment]
Apparently I misunderstood your idea. Now I see it contradicts the way MPIV has always been working so I don't think it should be implemented the way you proposed. Assuming I didn't misunderstand you again. Maybe the problem you want to solve can be solved differently.

As for the new fit modes, they simply replicate the existing functionality of custom scale factors to make the feature more user-friendly.

As for the bug you mentioned, looks like I didn't test automatic scaling properly...

**Comment by Ryujinra** [comment]
I can see how it would be non-consistent with the normal expected behavior which would be to show the original image size with the initial popup, or else enter zoom mode for it automatically.

I can basically achieve the same thing now if I set it to `zoom automatically` and `fit to window`, my only issue was this would lock the cursor into zoom mode even for images you don't want to zoom in anymore on, making it cumbersome to close the popup since it will stay up after no long hovering over the link. I can remedy this by selecting the option which closes the popup when fully zoomed out, and just scrolling down when im done viewing an image, so it's not a big deal. The main usefulness is having the `fit to window` option available at all.

Automatic zooming is mostly fixed now, but there remains a bug:  zooming in will occasionally stop working on smaller images which are automatically fit to the window initially. It will always fit it to window properly to begin with, but if you try to zoom in the popup just closes sometimes. Doesn't happen every single time, and is reproducible on the same link.

**Comment by tophf** [comment]
Fit to the window bug might be fixed now.

**Comment by Ryujinra** [comment]
Doesn't appear to have been fixed for me, but I noticed a bug that might be related or actually the same bug: sometimes the zoom status will get "stuck" even after closing the popup, such that when you hover over the thumbnail again, the full image is zoomed in to what it was zoomed at previously before the old popup closed. If you scroll up or down while the popup is closed, the hover the image again, its zoomed at the place you would expect had the popup been open the whole time. I think it is failing to properly clear the popup state after it is no long visible/closed.

**Comment by tophf** [comment]
Well, without a precise repro I'll have to keep trying then.

**Comment by Ryujinra** [comment]
Yeah it's not consistent, but once it breaks, zooming is pretty broken for the whole page. You can go to [old.reddit.com/r/pics](https://www.old.reddit.com/r/pics), hover zoom some images with automatic zoom/fit to window on, and you'll see it eventually will stop allowing you to zoom some images, and they will be zoomed in at whatever level they were at when last closed.

**Comment by tophf** [comment]
Hopefully fixed now.

**Comment by Ryujinra** [comment]
Almost fully fixed. For smaller images that are fit to the viewport, they will zoom in/out fine, but when you try to move the cursor to pan around the zoomed in image it just closes the popup.

**Comment by tophf** [comment]
I couldn't reproduce. 

![image](https://user-images.githubusercontent.com/1310400/75509463-be701780-59f8-11ea-950a-3d050d827a49.png)

**Comment by Ryujinra** [comment]
So the bug is not as consistent as I thought, so I found an image and a link you can use to reproduce it every time. Visit this page: [reddit tree picture](https://old.reddit.com/r/pics/?count=25&after=t3_fan7ed#) and hover the top post's thumbnail (of the tree). You can zoom in/out just fine, but if you move the mouse to pan, it will immediately close the popup.

**Comment by tophf** [comment]
Definitely works for me.
Could be another userscript or extension interefering.

**Comment by Ryujinra** [comment]
I found the issue. It breaks when the Firefox scaling setting `layout.css.devPixelsPerPx` is set beyond a certain point. I have mine set to "2.2" as I have a 4K screen. There is no issue all the way up to `2.1` scale factor. I'm not sure if you'll be able to reproduce by setting the scale factor to the same value (I'm probably crossing some threshold of a combination of DE scaling settings and browser scale).

**Comment by tophf** [comment]
Nope, can't repro, tried various values like 0.5, 1.5, 2.2, 4, 5 and a few others.
FWIW this could be even a bug in Firefox.

**Comment by tophf** [comment]
Looking [at the code ](https://github.com/tophf/mpiv/blob/master/script.user.js#L1708-L1723) the only case where the popup closes is when `ai.zoomed` is false i.e. the popup is not in the zoom mode, but that's the expected behavior.

**Comment by Ryujinra** [comment]
Yeah the problem for me is that the popup _should_ be in zoom mode when I'm zoomed in, but something is causing it to close the popup anyway when I try to pan on some images. I guess from what you've this is only possible if `ai.zoomed` is erroneously being set to `false`, or if `ai.zoomed` is being ignored and the popup is being closed regardless of zoom status in these cases. This only happens with DPIs greater than that value for me though, and I expect several different interactions could be going on behind the scenes with this option on, so it could very well be a Firefox bug in my setup.

**Comment by tophf** [comment]
Okay, so I guess we can close this thread. You can open a new issue on that dpi thing if you ever get another way of reproducing it for me.

**Comment by Ryujinra** [comment]
I'll close the issue, but as a last note, in case it is ever helpful, I am only able to reproduce the issue between dpi levels of 2.19 and 2.26, outside that narrow range I can't reproduce. Some very strange bug is likely at fault, but in the meantime I will just use a different DPI.
