### ISSUE TITLE
Randomly getting empty pages in twitter.com (Chrome only)

### ISSUE THREAD

**Issue by darkred** [tophf/mpiv#71]
The most unusual thing has been happening recently, since Chrome 93:
in only one site, twitter.com (I haven't noticed this in any other site) I'm *randomly* getting empty pages instead of twitter content.
Also, at that time, the Back/Forward browser buttons also display empty pages.

I've tried a lot to nail it down and I came up to the following:
I have managed to recreate it multiple times in a fresh 94 Chrome profile, with only Tampermonkey 4.13/Violentmonkey 2.13.0.5 beta installed and the script with its default settings.
There's never error in browser Console or in the extension's background page.

I couldn't reproduce it when having TM/VM disabled not even once. Also I couldn't reproduce it in Firefox.

By *randomly*, I mean that I (login to twitter.com and) navigate anywhere in twitter, 
from my timeline, to any profile, expand tweets, open my bookmarks, reload a twitter page, anything.

Here is a screenshot and a screen capture:
![](https://user-images.githubusercontent.com/723651/134590664-a962a57e-c992-499c-a69a-0d2c6e81358f.jpg)
![Animation99~](https://user-images.githubusercontent.com/723651/134590816-b12abf45-a1cc-408c-9a73-0e0d4b0a5aaf.gif)

&nbsp;
@tophf What do you think? I know it seems strange, but could it be something in MPIV that's causing this? Or in TM/VM itself??
Or maybe I should report it as a Chrome issue?

Unforturtunately I can't reproduce it consistently but it's been happening so many times, annoyingly often.

**Comment by tophf** [comment]
MPIV doesn't intercept navigation so I don't see how it could be related. So far it sounds like a bug in Chrome.

**Comment by tophf** [comment]
Try using https://www.chromium.org/developers/bisect-builds-py

**Comment by tophf** [comment]
Try disabling chrome://flags/#back-forward-cache

**Comment by Fawkes-Allen** [comment]
I tried disabling the flag and am still getting the issue. It seems most common when a tab is opened in the background. It seems fairly random when it happens with no consistency as reported. With Firefox, it has the same issue. Fresh install, only uBlock Origin and this script in Tampermonkey. This time it seems more consistent in that it will show a blank white page (barebones html skeleton with no doctype) the *first* time you middle click on a link to another person's profile/twitter from the page.

I have no idea why it is doing this, or why the script would be causing this since as you said, it shouldn't.

**Comment by tophf** [comment]
The only thing that might be related is CspSniffer. Try replacing these lines https://github.com/tophf/mpiv/blob/7631dd5ebd8ba67fa96d5f79d432033bdca34af2/script.user.js#L719-L723 with this:
```js
    this.init = this.initPending = null;
```

**Comment by darkred** [comment]
@tophf you are right: with this change the issue no longer occurs. Thank you.

**Comment by tophf** [comment]
Hmm, it probably means a bug in twitter's server. Could you help debugging it? Try the original code with this change: `fetch(location, {method: 'HEAD', cache: 'no-store'})` or just `fetch(location)`.

**Comment by Fawkes-Allen** [comment]
The first fetch substitution caused the problem to show up again. The second does seem to have stopped the issue. At least, I haven't noticed any blank pages since trying.

**Comment by darkred** [comment]
I confirm that the latter substitution fixes the issue. Thank you.
