### ISSUE TITLE
The new `"e"` advanced syntax `{".parent-selector": ".child-selector"}` causes `RangeError: Max call stack size exceeded`

### ISSUE THREAD

**Issue by Fawkes-Allen** [tophf/mpiv#72]
The newer advanced `"e"` syntax that allows the `{ "Parent":"Image" }` usage doesn't seem to actually work. I may be doing something wrong with the use of the command but for now it just seems to be running into a loop of: 
`adaptiveFind` - `runeE2` - `find` - `adaptiveFind` - `runE2` - ... and so on until I get a 
`RangeError: Maximum call stack size exceeded` error.

*The related commit: https://github.com/tophf/mpiv/commit/2054a38d838adb9e62b90f6176c77073307aad4c*

**Comment by tophf** [comment]
Example url/rule?
