### ISSUE TITLE
Commit "disable fade-in transition when flipping gallery" causes initial empty border/placeholder when flipping gallery

### ISSUE THREAD

**Issue by darkred** [tophf/mpiv#75]
I'm referring to commit https://github.com/tophf/mpiv/commit/1be7fd570f1621c0aa150b224c5dba535c473aa8
*The previous commit is: https://github.com/tophf/mpiv/commit/d27df29bdf684c50a7033718abc6a7f3714a14a6*

The above commit causes initial empty border/placeholder when flipping gallery. 

Test gallery URL: http://www.twilightsite.com/fantasy/Old/Royo/Royo.html
Test rule:
```json
{"d": "twilightsite.com",
 "e": "td > a:first-child",
 "s": "gallery",
 "g": {
  "image": "td > a:first-child",
  "index": "return node.href"
 }
}
```

Screenshot comparison between the two commits (tested having cache disabled):

<details>
<summary>Before:</summary>

![](https://user-images.githubusercontent.com/723651/136999903-0e1246dd-58a3-4022-9db5-051e2b89dbd2.gif)
</details>
<details>
<summary>After:</summary>

![](https://user-images.githubusercontent.com/723651/136999888-ee4c4a23-66f4-4e17-bf24-8aa43ce8cb1b.gif)
</details>

Thank you

**Comment by tophf** [comment]
If you enabled the option in Firefox, it fully reverses the change so whatever happens is unrelated and must be a bug in Firefox.

**Comment by darkred** [comment]
Yes, I have it enabled, and the issue occurs consistently even in a fresh Firefox profile. 
I even tried latest Firefox Nightly 95 and it also occurs consistently.

Should I make an issue in bugzilla.mozilla.org about this? Could you point please on what to report? How to describe this bug?

**Comment by tophf** [comment]
Ah, good. Thanks for the investigation.
