### ISSUE TITLE
Right-click to zoom doesn't work on WhatsApp Web

### ISSUE THREAD

**Issue by pintassilgo** [tophf/mpiv#81]
Shift to zoom works, but I'm used to use right-click and it doesn't work on WhatsApp Web, while it works on other websites. Probably WhatsApp Web has a click listener blocking MPIV. I guess this is fixable, because it works fine with Imagus (extension similar to MPIV).

Using the latest user.js from this repo. I use FireMonkey, but tried with VM and it's the same.

**Comment by tophf** [comment]
I don't have an account there so please try this tentative fix: [mpiv.txt](https://github.com/tophf/mpiv/files/7514352/mpiv.txt)

**Comment by pintassilgo** [comment]
It works. Thank you.

**Comment by pintassilgo** [comment]
Doesn't removing `passive` in `mousemove` and `wheel` hurt performance?

**Comment by tophf** [comment]
It was a leftover from the times when this event did **all** the work. Now it spends just a few microseconds to enqueue the event, which will be processed later, effectively just like a passive listener.

**Comment by tophf** [comment]
As for the wheel, it's attached only when the popup is shown to prevent scrolling the page.
