### ISSUE TITLE
randomly stopped working alltogether

### ISSUE THREAD

**Issue by ANaPhOrAX** [tophf/mpiv#82]
Worked for me yesterday, but today just does nothing.  Nothing was changed.

#### Environment
 - Browser: Chrome 95.0.4638.69 (Official Build) (64-bit)
 - MPIV Version: v1.2.12

**Comment by tophf** [comment]
Works for me. Show a screenshot of your `MPIV config` and give me at least one URL as an example.

**Comment by holysnipz** [comment]
Not sure if mine is the same case, but:

While MPIV is detecting and show larger image, but the image is stuck at top left of the browser, then the script broke.
Can't do anything else other than refresh and just don't trigger MPIV again. 

-------------------------------

**Chrome 95.0.4638.69 (Official Build) (64-bit)**
![image](https://user-images.githubusercontent.com/9103583/141286462-10d1c42a-b5b7-45a8-b131-e5023498fcdf.png)

**Firefox 94.0.1 (64-bit)**
![image](https://user-images.githubusercontent.com/9103583/141286764-b5dd6471-7ab1-4e54-a4c0-1c2933d91e65.png)

MPIV 1.2.12, Using Violentmonkey as script manager on both browsers

**Comment by tophf** [comment]
I've added a workaround in the new version 1.2.13 so just update it in Violentmonkey.

P.S. Thanks, @holysnipz. Looks like it's a bug in Violentmonkey that I can't reproduce with [its latest beta](https://github.com/violentmonkey/violentmonkey/releases).
