### ISSUE TITLE
Possibly not working with Twitter previews on Discord?

### ISSUE THREAD

**Issue by Jimi-James** [tophf/mpiv#83]
#### Steps to reproduce the bug
1. Mouseover an image in a Twitter preview thumbnail when someone posts a link to a tweet on Discord.

#### Expected behavior
The image should get a full-size popup like any other. Unfortunately, nothing happens for me.

#### Screenshots
Nothing to screenshot

#### Environment
 - Browser: Firefox
 - MPIV Version: 1.2.13

Not sure if this is just me since it seems like a pretty common use case.

Also odd: I'm getting the same behavior (no image popups) when I mouseover preview images in Greasy Fork--including the ones on this script's own page there: https://greasyfork.org/en/scripts/394820-mouseover-popup-image-viewer

**Comment by tophf** [comment]
I don't use either discord or twitter so my quick test shows it works. Can you provide a URL where it doesn't?

To view screenshots on GreasyFork you need to install a custom rule: open `MPIV config`, click `Install rule from repository...`, choose `Greasyfork`.

**Comment by Jimi-James** [comment]
In the case of Discord--there isn't any specific URL to provide. You can think of it as a domain-wide issue with a web app. You may already know Discord is a chat app? When someone sends a link to a tweet, a preview of that tweet is loaded inline. [Here's an example of what it looks like when that preview is of a tweet featuring an image](https://imgur.com/xMQGuXh).

Any other time an image or video shows up as a Discord preview, MPIV seems to work fine. But specifically when it's inside a preview of a tweet, no dice. It makes things a lot harder for me, as this is one of my primary uses for this script. I could go back to Imagus but Imagus is abandoned, so that's not a permanent solution.

I suppose solving this calls for someone who does use Discord, and who knows much more than me about hacking through modern image-rendering techniques on the web.

**Comment by tophf** [comment]
Well, I don't think I can fix it without investigating a live link.

**Comment by tophf** [comment]
I won't keep a nonreproducible issue open so just to confirm for the last time, can you give me a link that shows this bug or maybe it's possible to reproduce if you send me a twitter link via a personal message on discord (same nick)?

**Comment by Jimi-James** [comment]
Ah, you _do_ use Discord? Sure, I can send you a message with a link. I'd love to know whether I'm the only one too. I'm also the same nick--although, Discord requires that at least one of us have the other's 4 digits at the end of their nick to find them and send a message, AFAIK.

To get that info privately, in lieu of private messages on Github, apparently one of us can make a new dummy repo and @ the other person, which they'll get as a notification: https://stackoverflow.com/a/49277449/1570077

Would you rather do this or would you rather that I do it? Or let me know if you have a better idea.

**Comment by tophf** [comment]
I have an account but I don't use it. The number is 5327.

**Comment by darkred** [comment]
@tophf sorry for the off-topic. Given the opportunity, would it be I if contact you via pm in Discord? Or maybe via email?
I'd like to ask you something privately please. Not a favor or anything, of course. Just a question/advice from your experience.

**Comment by tophf** [comment]
I don't use discord so just email me @ gmx.com.
