### ISSUE TITLE
Flickr rule does not work when logged in.

### ISSUE THREAD

**Issue by Fawkes-Allen** [tophf/mpiv#84]
#### Steps to reproduce the bug
1. Log into Flickr and try to hover over an image.

#### Expected behavior
The Image would show up, same as if you were logged out.

#### Screenshots
![2021-11-30_18-27-46](https://user-images.githubusercontent.com/37897985/144144392-25ff09bb-fdc1-4634-9614-321373535fa6.png)

#### Environment
 - Browser: Chrome
 - MPIV Version: Current and previous versions

This seems to be an issue with the Site_Key being considered incorrect if logged in. I don't get why, but it gives a login/auth error.

**Comment by tophf** [comment]
Works for me.

**Comment by Fawkes-Allen** [comment]
I don't suppose you have requested a Flickr API key? https://www.flickr.com/services/api/keys/

I don't know why it won't work, other helpful information I can give

https://www.flickr.com/services/rest/?photo_id=51698255936&api_key=c7a531390d7515e272abd41b7d08d58a&method=flickr.photos.getSizes&format=json&nojsoncallback=1

This is the url it is trying to call, and the image below is what I get.
![2021-12-01_04-10-01](https://user-images.githubusercontent.com/37897985/144205248-48fc3b67-a141-4abf-9728-3ee33b78f8d0.png)

When logged out or Incognito, that url works fine.
![2021-12-01_04-14-15](https://user-images.githubusercontent.com/37897985/144205899-7161568f-f1c2-4a3c-9e00-40a33030868a.png)

**Comment by tophf** [comment]
I'm using the site's key and it works for all the images I can find on the site. It doesn't work for your image so I wonder what's different about it?

**Comment by Fawkes-Allen** [comment]
I used an image from the home page, but it doesn't work in a similar fashion no matter what image I hover over. Any photo ID I use will have the login error using the site key so long as I am logged in. I am just as confused and perplexed by what exactly Flickr's issue is when logged in for me and a few others I had try.

**Comment by tophf** [comment]
I'm using Violentmonkey beta.

**Comment by Fawkes-Allen** [comment]
I was previously using Tampermonkey, however, even after switching to Violentmonkey Beta, the same thing happens with the json response as long as I am logged into Flickr.

**Comment by tophf** [comment]
Try the current code, it enforces an anonymous mode.
https://github.com/tophf/mpiv/raw/master/script.user.js

**Comment by Fawkes-Allen** [comment]
That does it. I also found another method that involved grabbing the csrf token.
```
dotDomain.endsWith('.flickr.com') && {
	r: /flickr\.com\/photos\/[^/]+\/(\d+)/,
	s: m => `https://www.flickr.com/services/rest/?${
		new URLSearchParams({
			photo_id: m[1],
			csrf: unsafeWindow.YUI_config.flickr.csrf.token,
			api_key: unsafeWindow.YUI_config.flickr.api.site_key,
			method: 'flickr.photos.getSizes',
			format: 'json',
            nojsoncallback: 1,
		}).toString()}`,
	q: text => JSON.parse(text).sizes.size.pop().source,
}
```

The anonymous method however seems as if it could be useful for other websites/situations.

Thanks for working out a solution for the issue, since it seems to be such an esoteric one.
