### ISSUE TITLE
Option to not close fullzoom on page mouseout

### ISSUE THREAD

**Issue by pintassilgo** [tophf/mpiv#85]
I think there should be an option to prevent closing fullzoom on blur. I think the current behavior makes no sense because MPIV still works when you hover an image/link from a page that is visible but not focused. At least `visibilitychange` should be used instead.

Sometimes I need to read and write some chars from images. With Imagus (MPIV alternative) I right-click to zoom, switch to a text editor window and can do what I need. With MPIV I need to open the zoomed image in a standalone tab, because I can't keep it zoomed on page.

Another use case is if you're zooming a long video or a large image hosted on a slow/busy server. You may want to switch to another tab while the image/video loads. Or you may want to pause a long video to quickly do something on other tab...

**Comment by tophf** [comment]
MPIV doesn't listen to `blur` event. Please describe the exact sequence of actions so I can see what happens inside.

**Comment by pintassilgo** [comment]
Hadn't looked at the code, actually i guess it's `mouseout`.

1; Hover a *zoomable* element and right-click to enter *zoom mode*.
2. Move cursor out of the page (initially i thought it was on blur).
3. MPIV closes zoom mode.

**Comment by tophf** [comment]
Looking at the source code, I see you can hold `Shift` key while moving the mouse out of the page/window, which is the historical behavior of the original MPIV. Personally, I don't have a preference so I guess I'll try observing this particular case for a while before making a decision, but regardless of the outcome I'll probably add an option anyway.

**Comment by tophf** [comment]
Implemented in 5a51980a. I'll test it for a while first before publishing.
