### ISSUE TITLE
Embedded Disqus comments on third party sites in AdGuard

### ISSUE THREAD

**Issue by zubrRB** [tophf/mpiv#89]
Would like MPIV to zoom in on images in Disqus comments embedded on third party sites. https://www.comss.ru/page.php?id=9919

**Comment by tophf** [comment]
It works for me in Chrome.

**Comment by zubrRB** [comment]
Through AdGuard, images are enlarged in the comments feed on a personal Disqus profile, but this does not happen in inline comments on third-party sites.

https://user-images.githubusercontent.com/50718960/149328682-15c5654b-af94-4b5f-a4d3-2cf72e157c1b.mp4

**Comment by tophf** [comment]
I'm not using AdGuard so installing it each time is cumbersome for me. Maybe someone else will investigate it.

**Comment by zubrRB** [comment]
It also does not work when hovering on images on the official blog Disqus. https://github.com/AdguardTeam/CoreLibs/issues/1589

**Comment by zubrRB** [comment]
_EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src https:"._

**Comment by tophf** [comment]
I forgot there was a default built-in rule that disabled disqus for whatever reason I don't remember now. In a userscript manager like Tampermonkey the script can be configured and the ruled could be removed but apparently it's impossible in AdGuard. Anyway, I've removed the rule.

**Comment by zubrRB** [comment]
Script v1.2.20 started working on the Disqus blog, but never made it to work in his comments. 
https://blog.disqus.com/most-popular-food-website-minimalist-baker

**Comment by tophf** [comment]
I guess it means the issue is caused by a difference in AdGuard's implementation.

**Comment by zubrRB** [comment]
They are now just sorting out this point in the issue, to which I provided a link just above.
