### ISSUE TITLE
Request: For youtube.com / youtu.be links, popup the embedded version of the video

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#9]
Would it be possible to load the embedded video when hovering youtube/youtu.be links?

It is simple to get the embedded link from a standard youtube link; you just replace the string `watch?v=` with `embed/`, and you have the embedded version of the video.

For instance, `https://www.youtube.com/watch?v=aqz-KE-bpKQ` (Big Buck Bunny) would become `https://www.youtube.com/embed/aqz-KE-bpKQ`.

This would probably work for any site, since you just need to check the href attribute for a standard youtube link.

**Comment by tophf** [comment]
That would require showing an iframe, but MPIV is only for directly linkable images and videos. There are other extensions/scripts that can show youtube videos on hover so I don't think it should be added here.

**Comment by tophf** [comment]
FWIW There was a rule for youtube links in the rule installer UI but it no longer works now and only worked for some videos in the past and was limited to 720p. YouTube stopped providing mp4 universally quite a while ago, it's pretty random in my experience, so it'd be frustrating to have such a whimsical rule built-in.
