### ISSUE TITLE
Option to Exclude Videos from Ever Popping Up

### ISSUE THREAD

**Issue by npn225** [tophf/mpiv#94]
Would it be possible to add functionality so that videos never pop up while being hovered over?

A "Disable for Videos" button? Similar to the "Mute Videos" button.

If not, could I get the rule that would disable this userscript for all videos on all sites?

**Comment by tophf** [comment]
Since this is the first time I encounter such a use case, I'd say making a personal rule is the right solution. You can find which rules are activating for your videos by opening MPIV config, opening devtools console, and hovering the element in the page. The console will print the rule so you can copy its selectors into your rule in the config dialog that should also have `"s":""`.

**Comment by npn225** [comment]
Thanks for the quick response. 
Once again, I want to prevent pop-ups from ever happening whenever I hover the mouse over a video. 

I'm surprised that this is the first time you've ever encountered anyone asking for this. 

Personally, I just don't see why I (or anyone for that matter) would want a popup for an already playing video.

It's especially annoying when you are trying to use the mouse to click on a specific time in the time/progress bar, only to have the pop-up come out of nowhere. 

Overall though, this is a great userscript. 

At the bottom, below is the rule I have come up with but it is not working.

I have set "d" to "" so that the rule works on all domains.
I have also set "s" to "" so that rule is to not create a popup.

Now, how exactly do I use "e" to select for the video element tag?
What I have done below is obviously incorrect since it doesn't work.

{"name": "No popup for video tags",
 "d": "",
 "e": "*[data-mediatype='video'] > a",
 "s": ""
}

**Comment by tophf** [comment]
> for an already playing video

This is the bit I was missing.
Normally this script shows the preview when hovering a link, so not showing just videos is unusual.

Can you share a link to some site that exhibits the problem?

**Comment by npn225** [comment]
Hey @tophf, 

Here it is: [nsfw](shorturl.at/eoquQ)

The site is nsfw but the video is just a spider-man cartoon. 
The problem happens for all videos on this site whether using chromium or firefox browsers.

I will delete the link in this post once you reply.

**Comment by tophf** [comment]
Thanks. Fixed in the new version: videos will be previewed only if hovered with <kbd>Ctrl</kbd> being held.

**Comment by npn225** [comment]
> Thanks. Fixed in the new version: videos will be previewed only if hovered with Ctrl being held.

Final Question: Will this work universally or only for the site linked above?

Lastly: Thank you for your quick work and dedication.

**Comment by tophf** [comment]
1. It may work for all sites, but I can't be sure because players are different, sites are different, etc.
2. Depends on their [auto]update settings.

**Comment by npn225** [comment]
Alright! Thanks again!
