### ISSUE TITLE
Some improvements from Imagus like higher quality thumbnail previews

### ISSUE THREAD

**Issue by rieje** [tophf/mpiv#95]
I didn't realize Imagus wasn't open source so am looking to switch to mpiv. With some settings configured, it seems comparable, but there are some things I think Imagus does better that I'm wondering if mpiv can improve. The first two can be seen in this [screenshot](https://0x0.st/oTrH.png) where both Imagus and mpiv are displaying their images.

1) Higher quality thumbnails. The larger image higher quality image is produced by Imagus with its "preferred with the "YouTube (preview image)" setting enabled. When testing this, the difference in quality for some photos are very apparent while some are not so apparent (if I were to zoom the smaller image produced by mpiv to be the same size, it would be lower quality). Hovering over that Imagus settings says the following which may be useful if mpiv can implement this:

> Many hosts provide different sizes for the same image. The filters are able to create URLs for these images, and mark them as high (usually the original image) and low (mid-sized images, around 800-1024px) resolution.

> If this option is un-checked, then by default the low resolution will be shown, but switching between resolutions is possible at any time with the Tab key (or only in full-zoom by clicking on the dimensions in the caption).

> If showing image dimensions on caption is enabled, then the color of the dimensions (depending on the style of the caption) will be cyan or red for low resolution, indicating that (maybe) there is a larger image.

Also, Imagus usually shows the higher quality thumbnail without the black bars on the top/bottom of the thumbnails as seen in the screenshot which is quite nice. I think that's a product of being able to get the higher quality thumbnail from the source, doubt Imagus does additional processing on the image fetched.

2) When a thumbnail is shown on mpiv, there's a bar that fades to show the name of the content, resolution, etc. IMO, showing this directly on top of the expanded content like how it's done in Imagus is better. That information is related to the content you're viewing so it should be as close as possible to the content itself. Imagus does this and in a less intrusive way, without a fading effect which can be distracting. I would also rather disable the bar on top of the webpage that mpiv displays than to use it in its current state because I don't want an overlay on a webpage especially if it requires diverting your eyes from the content in the middle of the page to see this info at the top of the page.

3) mpiv seems to struggle with some gifs that Imagus doesn't. At https://old.reddit.com/r/gifs/, on at least the post titled "Cow mom", hovering it shows the gif in very low fps while the actual content is video-like in both the webpage it was hosted in and in Imagus. This issue is quite rare.

Thanks for your work.

**Comment by tophf** [comment]
Thanks for the feedback.

1. There is no such universal thing. The quality/size depends on a rule for this specific source. You can post a request with details/URL of the source in https://github.com/tophf/mpiv/discussions/categories/mpiv-host-rules
2. I agree but that's how MPIV has always worked, and I'm not really the author, I just maintain it, so rewriting it isn't simple. Maybe someday.
3. See 1.
