### ISSUE TITLE
Instagram image pop-up no longer works

### ISSUE THREAD

**Issue by MWP** [tophf/mpiv#99]
#### Steps to reproduce the bug
1. Hold mouse-over an instagram image

#### Expected behavior
Pop-up of large image

#### Environment
 - Browser: Vivaldi (latest stable), with Tampermonkey.
 - MPIV Version: 1.2.26

#### Notes
I'm not sure what insta have changed as yet. Whatever they did change, it stopped MPIV working about 1 week ago.

**Comment by tophf** [comment]
The site has removed its public API. I'll see what I can do...

**Comment by MWP** [comment]
This needs to be re-opened.
The older version of MPIV still works on instagram, but the current version does not.
Some change to MPIV since then has broken it.
